// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'actionCenter': string;

  'actionTable': string;

  'badgeApproved': string;

  'badgeDeclined': string;

  'badgePending': string;

  'cardBlue': string;

  'cardGold': string;

  'cardGreen': string;

  'cardInfo': string;

  'cardPurple': string;

  'chartCard': string;

  'chartContainer': string;

  'chartHeader': string;

  'chartSubtitle': string;

  'chartsGrid': string;

  'dashboard': string;

  'dashboardIntro': string;

  'iconContainer': string;

  'noDataMessage': string;

  'sectionHeader': string;

  'sectionSubtitle': string;

  'splitLayout': string;

  'statusBadge': string;

  'summaryCard': string;

  'summaryGrid': string;

  'summaryLabel': string;

  'summarySubtitle': string;

  'summaryValue': string;

  'tableWrapper': string;

}

declare const strings: IExportStyles;

export default strings;