// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'actionCenter': string;

  'actionTable': string;

  'badgeApproved': string;

  'badgeAssigned': string;

  'badgeDeclined': string;

  'badgeMaintenance': string;

  'badgePending': string;

  'badgeReturned': string;

  'cardBlue': string;

  'cardGold': string;

  'cardGreen': string;

  'cardInfo': string;

  'cardPurple': string;

  'chartCard': string;

  'chartContainer': string;

  'chartHeader': string;

  'chartIcon': string;

  'chartSubtitle': string;

  'chartTitleBlock': string;

  'chartsGrid': string;

  'dashboard': string;

  'dashboardHeader': string;

  'dashboardIntro': string;

  'emptyStateHint': string;

  'fadeInUp': string;

  'filterDropdown': string;

  'filtersRow': string;

  'headerDate': string;

  'headerLeft': string;

  'headerRight': string;

  'headerSubtitle': string;

  'headerTitle': string;

  'hide-on-mobile': string;

  'iconContainer': string;

  'm-0': string;

  'mb-1': string;

  'mb-2': string;

  'mb-3': string;

  'mb-4': string;

  'mb-5': string;

  'metricDivider': string;

  'metricItem': string;

  'metricsRow': string;

  'mt-1': string;

  'mt-2': string;

  'mt-3': string;

  'mt-4': string;

  'mt-5': string;

  'noDataMessage': string;

  'p-0': string;

  'p-1': string;

  'p-2': string;

  'p-3': string;

  'p-4': string;

  'p-5': string;

  'pulse': string;

  'quickActionBtn': string;

  'quickActions': string;

  'searchField': string;

  'sectionHeader': string;

  'sectionSubtitle': string;

  'shimmer': string;

  'show-only-on-mobile': string;

  'skeleton': string;

  'skeletonCard': string;

  'skeletonChart': string;

  'skeletonLine': string;

  'splitLayout': string;

  'statusBadge': string;

  'summaryCard': string;

  'summaryGrid': string;

  'summaryLabel': string;

  'summarySubtitle': string;

  'summaryValue': string;

  'tableCellJustification': string;

  'tableWrapper': string;

  'trendDown': string;

  'trendUp': string;

}

declare const strings: IExportStyles;

export default strings;