// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'actionButtonContainer': string;

  'actionGrid': string;

  'active': string;

  'appLayoutContainer': string;

  'assetCardHover': string;

  'card': string;

  'cardHeader': string;

  'contentContainer': string;

  'dark': string;

  'heroSection': string;

  'heroText': string;

  'inventoryManagement': string;

  'is-selected': string;

  'mainContent': string;

  'paginationButton': string;

  'paginationContainer': string;

  'paginationControls': string;

  'paginationInfo': string;

  'sidebarContainer': string;

  'sidebarNavItem': string;

  'smallText': string;

  'teams': string;

  'welcomeDiagramContainer': string;

}

declare const strings: IExportStyles;

export default strings;