import * as React from 'react';
import type { IInventoryManagementProps } from '../models/IInventoryManagementProps';
import { IInventoryItem } from '../models/IInventoryItem';
import { IRequest } from '../models/IRequest';
import { IEventLog } from '../models/IEventLog';
import { IReturnRequest } from '../models/IReturnRequest';
import { MessageBarType } from '@fluentui/react';
import "@pnp/sp/site-users/web";
import "@pnp/sp/site-groups/web";
import { IEmployee } from '../models/IEmployee';
import { INotification } from '../models/INotification';
import { IWorkflowPopupDetails } from './WorkflowPopup';
export interface IWorkflowPopupConfig {
    isOpen: boolean;
    title: string;
    stage: string;
    type: 'success' | 'info' | 'warning' | 'error';
    message: string;
    details?: IWorkflowPopupDetails;
}
export interface IInventoryManagementState {
    items: IInventoryItem[];
    employees: IEmployee[];
    requests: IRequest[];
    auditLogs: IEventLog[];
    userRole: 'Admin' | 'Inventory Manager' | 'Inventory Employee';
    previewRole?: 'Admin' | 'Inventory Manager' | 'Inventory Employee';
    roleGroups: string[];
    roleLoading: boolean;
    requestActionInProgressId?: string;
    requestSearchId: string;
    isAssetFormOpen: boolean;
    isRequestFormOpen: boolean;
    loading: boolean;
    auditLogsLoading: boolean;
    errorMessage?: string;
    isTrackingActionInProgress?: boolean;
    expandedUserEmail?: string;
    selectedTabKey?: string;
    readNotificationIds: string[];
    clearedNotificationIds: string[];
    selectedNotification?: INotification;
    isNotificationDetailsOpen: boolean;
    returnRequests: IReturnRequest[];
    returnRequestsLoading: boolean;
    auditLogsRefreshTrigger: number;
    selectedAssetForReturn: IInventoryItem | undefined;
    isReturnFormOpen: boolean;
    activeUserDisplayName: string;
    activeUserEmail: string;
    isIncidentFormOpen: boolean;
    selectedAssetForIncident: IInventoryItem | undefined;
    preselectedIncidentType?: string;
    syncInProgress?: boolean;
    syncMessage?: string;
    syncMessageType?: MessageBarType;
    diagnosticInfo?: string;
    selectedAdminRequest?: IRequest;
    isAdminPanelOpen?: boolean;
    adminSelectedAssetId?: string;
    adminComment?: string;
    sidebarCollapsed: boolean;
    reportsSelectedTab: string;
    reportsAssetTypeFilter: string;
    reportsStatusFilter: string;
    configSelectedTab: string;
    connectionStatuses: {
        [listTitle: string]: 'connected' | 'error' | 'testing';
    };
    connectionErrorMessages: {
        [listTitle: string]: string;
    };
    groupUsersList: {
        [groupName: string]: string[];
    };
    loadingGroupUsers: {
        [groupName: string]: boolean;
    };
    workflowPopup: IWorkflowPopupConfig;
    lastMockEmail?: {
        to: string[];
        subject: string;
        body: string;
    };
    editMockEmailTo: string;
    editMockEmailSubject: string;
    isSendingMockEmail: boolean;
    mockEmailSendError?: string;
    mockEmailSendSuccess: boolean;
}
export default class InventoryManagement extends React.Component<IInventoryManagementProps, IInventoryManagementState> {
    private _isRequestOwnedByCurrentUser;
    private _isAssetAssignedToCurrentUser;
    private _getNotifications;
    private _markNotificationAsRead;
    private _markAllNotificationsAsRead;
    private _clearNotification;
    private _clearAllNotifications;
    private _handleNotificationAction;
    constructor(props: IInventoryManagementProps);
    componentDidMount(): Promise<void>;
    componentWillUnmount(): void;
    private _handleMockEmailSent;
    private _handleEmailSendFailed;
    private _onSendMockEmail;
    private _resolveUserRole;
    private _loadInventory;
    private _loadRequests;
    private _loadAuditLogs;
    private _loadReturnRequests;
    private _onSubmitReturnRequest;
    private _onUpdateReturnRequestStatus;
    private _onAddAsset;
    private _onSubmitRequest;
    private _onApproveRequest;
    private _onRejectRequest;
    private _onApproveAsset;
    private _onAssignAssets;
    private _onSyncAssignedAssets;
    private _onRunDiagnostics;
    private _exportWarrantyReportToExcel;
    private _exportWarrantyReportToPDF;
    private _exportDetailedReportToExcel;
    private _exportDetailedReportToPDF;
    private _testListConnection;
    private _loadGroupUsers;
    private _renderRequestAnalysis;
    private _renderAssetAnalysis;
    private _renderNotificationDetailsPanel;
    private _onAdminAssetChange;
    private _handleAdminAssignAndApprove;
    private _handleAdminReject;
    private _renderAdminAssignmentPanel;
    render(): React.ReactElement<IInventoryManagementProps>;
}
//# sourceMappingURL=InventoryManagement.d.ts.map