// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'actions': string;

  'brandSection': string;

  'divider': string;

  'logoContainer': string;

  'nexerHeader': string;

  'panelHeader': string;

  'subtitle': string;

  'title': string;

  'titleContainer': string;

}

declare const strings: IExportStyles;

export default strings;