define([], function() {
  return {
    "PropertyPaneDescription": "Ustawienia zarządzania inwentarzem",
    "BasicGroupName": "Ustawienia ogólne",
    "DescriptionFieldLabel": "Lokalizacja inwentarza",
    "AppLocalEnvironmentSharePoint": "Aplikacja działa w środowisku lokalnym jako składnik WebPart SharePoint",
    "AppLocalEnvironmentTeams": "Aplikacja działa w środowisku lokalnym jako aplikacja Microsoft Teams",
    "AppLocalEnvironmentOffice": "Aplikacja działa w środowisku lokalnym w witrynie office.com",
    "AppLocalEnvironmentOutlook": "Aplikacja działa w środowisku lokalnym w programie Outlook",
    "AppSharePointEnvironment": "Aplikacja działa na stronie SharePoint",
    "AppTeamsTabEnvironment": "Aplikacja działa w Microsoft Teams",
    "AppOfficeEnvironment": "Aplikacja działa w witrynie office.com",
    "AppOutlookEnvironment": "Aplikacja działa w programie Outlook",
    "UnknownEnvironment": "Aplikacja działa w nieznanym środowisku",

    "Common": {
      "Save": "Zapisz",
      "Cancel": "Anuluj",
      "Close": "Zamknij",
      "Submit": "Wyślij",
      "Approve": "Zatwierdź",
      "Reject": "Odrzuć",
      "View": "Podgląd",
      "ViewDetails": "Zobacz szczegóły",
      "Details": "Szczegóły",
      "Edit": "Edytuj",
      "Delete": "Usuń",
      "Add": "Dodaj",
      "Search": "Szukaj",
      "Loading": "Ładowanie...",
      "Processing": "Przetwarzanie...",
      "Reset": "Resetuj",
      "ResetFilters": "Resetuj",
      "ClearFilters": "Wyczyść filtry",
      "Actions": "Akcje",
      "Status": "Status",
      "Download": "Pobierz",
      "ExportExcel": "Eksportuj do Excela",
      "ExportPDF": "Eksportuj do PDF",
      "Yes": "Tak",
      "No": "Nie",
      "NotAvailable": "Nie dotyczy",
      "None": "Brak",
      "Unknown": "Nieznany",
      "All": "Wszystkie",
      "ErrorLabel": "Błąd:",
      "DismissError": "Odrzuć błąd",
      "LanguageLabel": "Język"
    },

    "Nav": {
      "Header": "Nawigacja",
      "RoleLabel": "Rola: {0}",
      "Dashboard": "Panel główny",
      "MyWorkspace": "Mój obszar roboczy",
      "Notifications": "Powiadomienia",
      "IncidentHistory": "Historia zgłoszeń",
      "ReplacementHistory": "Historia wymian",
      "Inventory": "Inwentarz",
      "Approvals": "Zatwierdzenia",
      "AssetAssignmentQueue": "Kolejka przydziału zasobów",
      "AssetReturns": "Zwroty zasobów",
      "EventStream": "Dziennik zdarzeń",
      "Reports": "Raporty",
      "Config": "Konfiguracja",
      "GroupMain": "GŁÓWNE",
      "GroupManagement": "ZARZĄDZANIE",
      "GroupSystem": "SYSTEM",
      "Expand": "Rozwiń",
      "Collapse": "Zwiń",
      "ToggleNavigation": "Przełącz menu nawigacyjne",
      "MainNavigation": "Nawigacja główna"
    },

    "Roles": {
      "Admin": "Administrator",
      "InventoryManager": "Kierownik magazynu",
      "InventoryEmployee": "Pracownik magazynu"
    },

    "Hero": {
      "Title": "Zarządzanie inwentarzem",
      "WelcomeBack": "Witaj ponownie, {0}!",
      "RoleLabel": "Rola: {0}",
      "LocationLabel": "Lokalizacja: {0}",
      "SharePointGroupsLabel": "Grupy SharePoint: {0}"
    },

    "Dropdowns": {
      "AssetType": {
        "Laptop": "Laptop",
        "Monitor": "Monitor",
        "Mouse": "Mysz",
        "Keyboard": "Klawiatura",
        "Headset": "Zestaw słuchawkowy",
        "Other": "Inne"
      },
      "AssetCondition": {
        "New": "Nowy",
        "Excellent": "Doskonały",
        "Good": "Dobry",
        "Fair": "Zadowalający",
        "Poor": "Słaby",
        "Damaged": "Uszkodzony"
      },
      "IncidentType": {
        "HardwareIssue": "Problem sprzętowy",
        "SoftwareIssue": "Problem z oprogramowaniem",
        "NetworkIssue": "Problem z siecią",
        "AssetDamage": "Uszkodzenie zasobu",
        "ReplacementRequest": "Wniosek o wymianę",
        "AccessIssue": "Problem z dostępem",
        "LoginIssue": "Problem z logowaniem",
        "PerformanceIssue": "Problem z wydajnością",
        "EmailIssue": "Problem z pocztą e-mail",
        "PrinterIssue": "Problem z drukarką",
        "Other": "Inne"
      },
      "IncidentPriority": {
        "Low": "Niski",
        "Medium": "Średni",
        "High": "Wysoki",
        "Critical": "Krytyczny"
      },
      "IncidentStatus": {
        "Open": "Otwarte",
        "InProgress": "W toku",
        "Resolved": "Rozwiązane",
        "Closed": "Zamknięte"
      },
      "ReturnCondition": {
        "Good": "Dobry (brak uszkodzeń, w pełni sprawny)",
        "Fair": "Zadowalający (niewielkie zużycie, w pełni sprawny)",
        "Poor": "Słaby (znaczne zużycie, wymaga naprawy)",
        "Damaged": "Uszkodzony (zepsuty, niesprawny)"
      },
      "ReturnRequestStatus": {
        "Pending": "Oczekujące",
        "Approved": "Zatwierdzone",
        "Rejected": "Odrzucone",
        "Completed": "Zakończone"
      },
      "AssetRequestPriority": {
        "Low": "Niski",
        "Medium": "Średni",
        "High": "Wysoki"
      },
      "AssetRequestStatus": {
        "PendingManagerApproval": "Oczekuje na zatwierdzenie przez kierownika",
        "ApprovedByManager": "Zatwierdzone przez kierownika",
        "Rejected": "Odrzucone",
        "AssetAssigned": "Zasób przydzielony"
      },
      "WarrantyStatus": {
        "Active": "Aktywna",
        "ExpiringSoon": "Wkrótce wygasa",
        "Expired": "Wygasła",
        "Unknown": "Nieznana"
      },
      "AuditLogDateRange": {
        "All": "Cały czas",
        "Today": "Dzisiaj",
        "Yesterday": "Wczoraj",
        "Last7": "Ostatnie 7 dni",
        "Last15": "Ostatnie 15 dni",
        "Last30": "Ostatnie 30 dni",
        "Last60": "Ostatnie 60 dni",
        "Last90": "Ostatnie 90 dni",
        "ThisWeek": "Ten tydzień",
        "ThisMonth": "Ten miesiąc",
        "Custom": "Niestandardowy zakres dat"
      },
      "AuditLogModule": {
        "All": "Wszystkie moduły",
        "Inventory": "Inwentarz",
        "Requests": "Wnioski",
        "Returns": "Zwroty",
        "Users": "Użytkownicy",
        "Reports": "Raporty",
        "Configuration": "Konfiguracja",
        "Notifications": "Powiadomienia"
      },
      "AuditLogStatus": {
        "All": "Wszystkie statusy",
        "Pending": "Oczekujące",
        "Approved": "Zatwierdzone",
        "Rejected": "Odrzucone",
        "Assigned": "Przydzielone",
        "Returned": "Zwrócone",
        "Completed": "Zakończone"
      },
      "AuditLogSort": {
        "NewestFirst": "Od najnowszych",
        "OldestFirst": "Od najstarszych",
        "AssetNameAZ": "Nazwa zasobu A-Z",
        "AssetNameZA": "Nazwa zasobu Z-A",
        "UserAZ": "Użytkownik A-Z",
        "UserZA": "Użytkownik Z-A"
      },
      "IncidentRaisedTo": {
        "Admin": "Administrator"
      }
    },

    "Lifecycle": {
      "RequestAsset": "Wniosek o zasób IT",
      "Acquisition": "Zakup zasobu",
      "Deployment": "Wdrożenie i przydział",
      "Support": "Bieżące wsparcie i konserwacja",
      "EndOfLife": "Koniec eksploatacji i utylizacja",
      "BadgeTitle": "Zasób IT",
      "BadgeSubtitle": "Cykl życia"
    },

    "Dashboard": {
      "AdminTitle": "Panel administratora",
      "ManagerTitle": "Panel kierownika",
      "EmployeeTitle": "Mój panel",
      "RoleAdministrator": "Administrator",
      "RoleManager": "Kierownik magazynu",
      "RoleEmployee": "Pracownik",
      "OverviewSuffix": "Przegląd",
      "RealTimeAnalytics": "Analizy w czasie rzeczywistym",
      "ActionViewInventory": "Zobacz inwentarz",
      "ActionAssignmentQueue": "Kolejka przydziału",
      "ActionReports": "Raporty",
      "ActionEventStream": "Dziennik zdarzeń",
      "ActionReviewApprovals": "Przejrzyj zatwierdzenia",
      "ActionAssetReturns": "Zwroty zasobów",
      "ActionMyWorkspace": "Mój obszar roboczy",
      "ActionNotifications": "Zobacz powiadomienia",
      "ManagerBannerTitle": "Panel kierownika magazynu",
      "ManagerBannerTextBefore": "— Wskaźniki wizualne i kolejki zatwierdzeń są agregowane na podstawie list wniosków. Pełne dane znajdują się w rejestrze ",
      "ManagerBannerTextAfter": ".",
      "AdminBannerTitle": "Panel administratora",
      "AdminBannerText": "— Analizy pochodzą bezpośrednio z fizycznych pozycji inwentarza. Wskaźniki przydziału pokazują pozycje zatwierdzone przez administratora.",
      "EmployeeBannerTitle": "Centrum zasobów osobistych",
      "EmployeeBannerText": "— Telemetria w czasie rzeczywistym śledząca przydzielone urządzenia i status bieżących wniosków.",
      "TotalAssets": "Wszystkie zasoby",
      "MyDevices": "Moje urządzenia",
      "AllocationRateSubtitle": "Wskaźnik przydziału: {0}% przydzielone",
      "AssignedHardwareSubtitle": "{0} przydzielonych urządzeń",
      "ItemsInCatalogSubtitle": "{0} pozycji w katalogu",
      "AvailableAssets": "Dostępne zasoby",
      "InStockSubtitle": "{0} w magazynie ({1}% całości)",
      "RequestsInQueue": "Wnioski w kolejce",
      "MyRequests": "Moje wnioski",
      "TotalRequests": "Wszystkie wnioski",
      "QueueRequestsSubtitle": "{0} wniosków w kolejce",
      "ApprovalSuccessSubtitle": "Skuteczność zatwierdzeń: {0}%",
      "AwaitingApproval": "Oczekuje na zatwierdzenie",
      "PendingRequests": "Oczekujące wnioski",
      "RequiresReviewSubtitle": "{0} wymaga przeglądu",
      "UnderReviewSubtitle": "{0} w trakcie przeglądu przydziału",
      "RequestsInApprovalQueueLabel": "Wnioski w kolejce zatwierdzeń",
      "AssetsByStatusLabel": "Zasoby według statusu",
      "NoDataLabel": "Brak danych",
      "NoAssetsLabel": "Brak zasobów",
      "NumberOfAssetsLabel": "Liczba zasobów",
      "NoApprovedRequestsYetLabel": "Brak jeszcze zatwierdzonych wniosków",
      "AssignmentStatusApprovedLabel": "Status przydziału (wnioski zatwierdzone)",
      "RequestsByStatusLabel": "Wnioski według statusu",
      "KpiRegionAriaLabel": "Kluczowe wskaźniki wydajności",
      "ApprovalsQueueStatusTitle": "Status kolejki zatwierdzeń",
      "ApprovalsQueueStatusSubtitle": "Wnioski pogrupowane według stanu zatwierdzenia przez kierownika",
      "AssetStatusDistributionTitle": "Rozkład statusów zasobów",
      "AssetStatusDistributionSubtitle": "Aktualny stan i status zarejestrowanych zasobów",
      "AssetsByTypeTitle": "Zasoby według typu",
      "AssetsByTypeSubtitle": "Rozkład kategorii sprzętu",
      "PostApprovalAssignmentTitle": "Status przydziału po zatwierdzeniu",
      "RequestFulfillmentTitle": "Status realizacji wniosków",
      "PostApprovalAssignmentSubtitle": "Status wydania zasobów dla wniosków zatwierdzonych przez kierownika",
      "RequestFulfillmentSubtitle": "Aktualny status we wszystkich procesach wniosków",
      "AdminActionCenterTitle": "Centrum działań — przydział zasobów",
      "AdminActionCenterSubtitle": "Ostatnie wnioski zatwierdzone przez kierownika oczekujące na fizyczne wydanie sprzętu przez administratorów",
      "ColRequester": "Wnioskodawca",
      "ColAssetRequested": "Żądany zasób",
      "ColQty": "Ilość",
      "ColDateApproved": "Data zatwierdzenia",
      "ColStatusAction": "Działanie statusu",
      "BadgeAwaitingHandoff": "Oczekuje na wydanie",
      "AdminEmptyState": "Wszystkie przydziały zrealizowane! Brak oczekujących wydań sprzętu.",
      "AdminEmptyStateHint": "Sprawdź kolejkę przydziału, aby zobaczyć dane historyczne",
      "ManagerActionCenterTitle": "Oczekujące decyzje kierownika",
      "ManagerActionCenterSubtitle": "Ostatnie wnioski pracowników oczekujące na Twoje zatwierdzenie lub odrzucenie",
      "ColDateRequested": "Data wniosku",
      "ColReason": "Powód / Uzasadnienie",
      "NoJustificationSpecified": "Nie podano uzasadnienia",
      "ColActionState": "Stan działania",
      "BadgeAwaitingApproval": "Oczekuje na zatwierdzenie",
      "ManagerEmptyState": "Brak oczekujących wniosków! Twoja kolejka zatwierdzeń jest pusta.",
      "ManagerEmptyStateHint": "Nowe wnioski pojawią się tutaj automatycznie",
      "EmployeeActionCenterTitle": "Status aktywnych wniosków",
      "EmployeeActionCenterSubtitle": "Ostatnie wnioski o sprzęt w trakcie weryfikacji",
      "ColAsset": "Zasób",
      "ColManagerName": "Imię i nazwisko kierownika",
      "ColManagerComment": "Komentarz kierownika",
      "ColFulfillmentState": "Stan realizacji",
      "BadgeAwaitingReview": "Oczekuje na przegląd",
      "BadgeCompletedAssigned": "Zakończone i przydzielone",
      "BadgeApprovedAwaitingHandoff": "Zatwierdzone, oczekuje na wydanie",
      "BadgeDeclined": "Odrzucone",
      "EmployeeEmptyState": "Brak ostatnio złożonych aktywnych wniosków.",
      "EmployeeEmptyStateHint": "Użyj opcji „Wniosek o zasób”, aby złożyć nowy wniosek",
      "MyEquipmentTitle": "Mój przydzielony sprzęt",
      "MyEquipmentSubtitle": "Sprzęt aktualnie zarejestrowany i przydzielony Tobie",
      "ColDeviceName": "Nazwa urządzenia",
      "ColCategory": "Kategoria",
      "ColSerialNumber": "Numer seryjny",
      "ColAssignedDate": "Data przydziału",
      "MyEquipmentEmptyState": "Obecnie nie masz przydzielonego żadnego sprzętu.",
      "MyEquipmentEmptyStateHint": "Przydzielone urządzenia pojawią się tutaj po wydaniu",
      "AttentionTitle": "Wymaga uwagi",
      "AttentionAllClear": "Wszystko w porządku, nic na Ciebie nie czeka",
      "AttentionWaitingAssignment": "Czekające na zasób: {0}",
      "AttentionAwaitingDecision": "Czekające na Twoją decyzję: {0}",
      "AttentionOverdue": "Po terminie: {0}",
      "AttentionInReview": "W przeglądzie: {0}",
      "AttentionReadySoon": "Zatwierdzone, zasób w drodze: {0}",
      "KpiInReview": "W przeglądzie",
      "KpiInReviewSubtitle": "Czeka na menedżera",
      "KpiAwaitingHandoff": "Czeka na wydanie",
      "KpiAwaitingHandoffSubtitle": "Zatwierdzone, zasób w przygotowaniu",
      "ViewAll": "Pokaż wszystkie ({0})"
    },

    "WorkflowPopup": {
      "GotIt": "Rozumiem",
      "LabelRequestId": "ID wniosku",
      "LabelReplacementId": "ID wymiany",
      "LabelIncidentId": "ID zgłoszenia",
      "LabelAsset": "Zasób",
      "LabelRequester": "Wnioskodawca",
      "LabelManagerName": "Imię i nazwisko kierownika",
      "LabelWorkflowStatus": "Status procesu",
      "LabelDate": "Data",
      "LabelCondition": "Stan",
      "LabelManagerAdminNotes": "Uwagi kierownika / administratora"
    },

    "Notifications": {
      "FilterAriaLabel": "Filtruj powiadomienia",
      "TabAll": "Wszystkie",
      "TabRequests": "Wnioski",
      "TabAssignments": "Przydziały",
      "TabSystemAlerts": "Alerty systemowe",
      "MarkAllAsRead": "Oznacz wszystkie jako przeczytane",
      "ClearFiltered": "Wyczyść przefiltrowane",
      "AllCaughtUpTitle": "Wszystko na bieżąco!",
      "EmptyStateMessage": "Nie znaleziono powiadomień w kategorii „{0}”.",
      "CategoryAll": "Wszystkie",
      "CategoryRequests": "Wnioski",
      "CategoryAssignments": "Przydziały",
      "CategoryAudits": "Audyty",
      "ViewDetails": "Zobacz szczegóły",
      "MarkAsRead": "Oznacz jako przeczytane",
      "DismissNotification": "Odrzuć powiadomienie",
      "FilterUnread": "Nieprzeczytane",
      "SearchPlaceholder": "Szukaj powiadomień",
      "GroupToday": "Dzisiaj",
      "GroupYesterday": "Wczoraj",
      "GroupThisWeek": "Wcześniej w tym tygodniu",
      "GroupOlder": "Starsze",
      "TimeJustNow": "Przed chwilą",
      "TimeMinutesAgo": "{0} min temu",
      "TimeHoursAgo": "{0} godz. temu",
      "TimeYesterday": "Wczoraj",
      "UnreadSummary": "Masz nieprzeczytane powiadomienia: {0}.",
      "UnreadSummaryOne": "Masz 1 nieprzeczytane powiadomienie.",
      "NoUnreadSummary": "Wszystko przeczytane.",
      "MarkAsUnread": "Oznacz jako nieprzeczytane",
      "DismissShown": "Odrzuć widoczne",
      "DismissedOne": "Powiadomienie odrzucone.",
      "DismissedMany": "Odrzucone powiadomienia: {0}.",
      "Undo": "Cofnij",
      "ShowMore": "Pokaż więcej (pozostało: {0})",
      "OpenPage": "Otwórz: {0}",
      "NoSearchResultsTitle": "Brak wyników",
      "NoSearchResults": "Żadne powiadomienie nie pasuje do \"{0}\".",
      "EmptyUnread": "Nie masz nieprzeczytanych powiadomień.",
      "OpenButtonUnreadAria": "Powiadomienia, nieprzeczytane: {0}"
    },

    "AssetForm": {
      "HeaderAdmin": "Dodaj nowy zasób",
      "HeaderManager": "Zarejestruj nowy zasób",
      "ManagerHint": "Rejestrujesz nowy zasób. Po dodaniu możesz przydzielić go pracownikom w sekcji Śledzenie zasobów.",
      "LabelTitle": "Tytuł (Grupa/Kategoria)",
      "LabelAssetName": "Nazwa zasobu",
      "LabelAssetType": "Typ zasobu",
      "LabelSerialNumber": "Numer seryjny",
      "LabelPurchaseDate": "Data zakupu",
      "LabelVendor": "Dostawca",
      "VendorPlaceholder": "Np. Dell, Apple, Microsoft, Lenovo",
      "LabelCondition": "Stan",
      "LabelWarrantyExpiry": "Data wygaśnięcia gwarancji",
      "LabelSpecifications": "Specyfikacja",
      "SpecificationsPlaceholder": "Np. Intel i7, 16GB RAM, 512GB SSD, itp.",
      "AddAsset": "Dodaj zasób"
    },

    "RequestForm": {
      "HeaderText": "Wniosek o zasób",
      "OnBehalfHint": "Wnioskujesz o ten zasób dla siebie. Składanie wniosków w imieniu innych użytkowników jest wyłączone.",
      "LabelRequester": "Wnioskodawca",
      "LabelEmployeeId": "Numer pracownika",
      "LabelManagerName": "Imię i nazwisko kierownika",
      "ManagerNamePlaceholder": "Wpisz imię i nazwisko kierownika",
      "ManagerNameRequired": "Imię i nazwisko kierownika jest wymagane",
      "ManagerSearchPlaceholder": "Szukaj menedżerów po nazwisku lub adresie e-mail",
      "ManagerSuggestionsHeader": "Menedżerowie w grupie {0}",
      "ManagerNoResults": "Brak pasującego menedżera. Tylko członkowie grupy {0} mogą zatwierdzać wnioski.",
      "ManagerSearching": "Wyszukiwanie...",
      "ManagerGroupUnavailable": "Nie udało się wczytać menedżerów z grupy {0}. Odśwież stronę lub poproś administratora o sprawdzenie grupy.",
      "LabelRequestedDate": "Data wniosku",
      "LabelAssetType": "Typ zasobu",
      "LabelPriority": "Priorytet",
      "LabelQuantity": "Ilość",
      "LabelReason": "Powód wniosku",
      "ReasonRequired": "Powód wniosku jest wymagany",
      "SubmitRequest": "Wyślij wniosek",
      "TypeInProgress": "{0} (wniosek w toku)",
      "OpenRequestItem": "{0} ({1}, {2})",
      "OpenRequestsNote": "Masz już wniosek w toku dla: {0}. O ten sam typ zasobu można wnioskować ponownie po przypisaniu zasobu lub odrzuceniu wniosku.",
      "DuplicateBlocked": "Masz już otwarty wniosek o {0} ({1}). Musi zostać zrealizowany lub odrzucony, zanim ponownie zawnioskujesz o ten typ zasobu.",
      "DuplicateTitle": "Wniosek nie został wysłany",
      "DuplicateStage": "Zduplikowany wniosek"
    },

    "ReturnAssetForm": {
      "HeaderText": "Wniosek o zwrot zasobu",
      "AssetInfoTitle": "Informacje o zasobie",
      "LabelAssetName": "Nazwa zasobu",
      "LabelSerialNumber": "Numer seryjny",
      "LabelType": "Typ",
      "LabelCurrentCondition": "Obecny stan",
      "LabelReturnedCondition": "Stan zwracanego zasobu",
      "LabelReturnReason": "Powód zwrotu",
      "ReturnReasonPlaceholder": "Opisz, dlaczego zwracasz ten zasób (np. otrzymano nowszy model, awaria sprzętu, zakończenie umowy...)",
      "ReturnReasonRequired": "Powód jest wymagany",
      "SubmitRequest": "Wyślij wniosek",
      "ErrorPrefix": "Błąd:",
      "GenericSubmitError": "Nie udało się złożyć wniosku o zwrot."
    },

    "IncidentRequestModule": {
      "HeaderReplacement": "Wniosek o wymianę zasobu",
      "HeaderIncident": "Zgłoś incydent",
      "NoAssetsReplacementInfo": "Obecnie nie masz przypisanych zasobów, dla których można złożyć wniosek o wymianę.",
      "NoAssetsIncidentInfo": "Obecnie nie masz przypisanych zasobów. Nadal możesz zgłaszać ogólne incydenty.",
      "LabelEmployeeName": "Imię i nazwisko pracownika",
      "LabelSelectAsset": "Wybierz przypisany zasób",
      "PlaceholderLoadingAssets": "Ładowanie zasobów...",
      "PlaceholderChooseAsset": "Wybierz jeden z przypisanych zasobów",
      "LabelAssetName": "Nazwa zasobu",
      "LabelSerialNo": "Numer seryjny",
      "LabelIssueType": "Typ problemu",
      "PlaceholderIssueType": "Wybierz typ problemu",
      "LabelPriority": "Priorytet",
      "LabelReasonForReplacement": "Powód wymiany",
      "LabelDescription": "Opis",
      "PlaceholderReasonForReplacement": "Opisz powód wymiany...",
      "PlaceholderDescribeIssue": "Opisz problem...",
      "LabelRaisedTo": "Zgłoszono do",
      "PlaceholderSelectTeam": "Wybierz zespół",
      "LabelRaisedDate": "Data zgłoszenia",
      "LabelStatus": "Status",
      "RequestReplacement": "Wniosek o wymianę",
      "ReportIncident": "Zgłoś incydent",
      "Cancel": "Anuluj",
      "ValidationRequiredFields": "Proszę wypełnić wszystkie wymagane pola.",
      "ErrorPrefix": "Błąd:",
      "GenericSubmitError": "Nie udało się zgłosić incydentu. Spróbuj ponownie."
    },

    "AssetTracking": {
      "NoPermission": "Nie masz uprawnień do sekcji Śledzenie zasobów. Tylko administratorzy i menedżerowie mogą przypisywać zasoby.",
      "SelectEmployee": "Wybierz pracownika",
      "PlaceholderSelectEmployee": "Wybierz pracownika, aby zobaczyć zasoby",
      "CurrentlyAssignedTo": "Obecnie przypisane do {0}",
      "ColAssetName": "Nazwa zasobu",
      "ColType": "Typ",
      "ColSerialNumber": "Numer seryjny",
      "ColStatus": "Status",
      "ColAssignedDate": "Data przypisania",
      "NotAvailable": "Nie dotyczy",
      "NoAssetsAssigned": "Ten pracownik nie ma obecnie przypisanych zasobów."
    },

    "ConfigPage": {
      "HeaderTitle": "Konfiguracja i zarządzanie listami",
      "HeaderSubtitle": "Centrum administracyjne do monitorowania list SharePoint, walidacji schematu, grup dostępu i konserwacji danych.",
      "TabSyncOperations": "Konserwacja",
      "TabListConnections": "Połączenia list",
      "TabRbacGroups": "Grupy dostępu",
      "TabSchemaGuides": "Walidacja schematu",
      "OperationsTitle": "Zarządzanie i synchronizacja listy mapowania",
      "OperationsDescBefore": "Upewnij się, że wszystkie zasoby obecnie przypisane do aktywnych pracowników są poprawnie zmapowane na liście SharePoint",
      "OperationsDescAfter": "Użyj poniższych przycisków, aby wykonać ręczne sprawdzenie synchronizacji lub zdiagnozować schemat bazy danych listy.",
      "SyncButtonProcessing": "Przetwarzanie...",
      "SyncButtonDefault": "Synchronizuj przypisane zasoby",
      "DiagnosticsButtonChecking": "Sprawdzanie schematu...",
      "DiagnosticsButtonDefault": "Uruchom diagnostykę schematu",
      "DiagnosticLogLabel": "Wynik dziennika diagnostycznego:",
      "ConnectionsTitle": "Połączenia list SharePoint",
      "ConnectionsDesc": "Każda lista jest wyszukiwana pod tymi samymi nazwami, których aplikacja używa w działaniu, a następnie sprawdzane są dostęp, Twoje uprawnienia i wymagane kolumny.",
      "ListTitle_InventoryList": "Lista inwentarza",
      "ListDesc_InventoryList": "Przechowuje główny katalog wszystkich zasobów fizycznych i sprzętu.",
      "ListTitle_RequestList": "Lista wniosków",
      "ListDesc_RequestList": "Zarządza zgłoszeniami pracowników, historią przepływów pracy i kolejkami przypisań.",
      "ListTitle_AssetReturnRequestList": "Lista wniosków o zwrot zasobów",
      "ListDesc_AssetReturnRequestList": "Obsługuje formularze zwrotu zasobów, kontrole przy zwrocie i zatwierdzenia przez menedżera.",
      "ListTitle_MappingList": "Lista mapowania",
      "ListDesc_MappingList": "Utrzymuje aktywne mapowanie przypisań w czasie rzeczywistym na potrzeby automatycznych kontroli zwolnienia.",
      "ErrorLabel": "Błąd:",
      "StatusVerifying": "Weryfikowanie...",
      "StatusConnected": "Połączono",
      "StatusFailed": "Niepowodzenie",
      "StatusNotVerified": "Niezweryfikowano",
      "TestLiveButton": "Testuj na żywo",
      "RbacTitle": "Kontrola dostępu oparta na rolach (RBAC)",
      "RbacDesc": "Sprawdź grupy użytkowników pobrane z SharePoint w celu weryfikacji poziomu uprawnień.",
      "RoleLabel_Owners": "Administrator",
      "RoleDesc_Owners": "Pełne uprawnienia administracyjne do modyfikowania zasobów, zatwierdzania zwrotów i zarządzania ustawieniami połączenia z bazą danych.",
      "RoleLabel_Members": "Menedżer inwentarza",
      "RoleDesc_Members": "Dostęp do zapisu w celu tworzenia elementów, przetwarzania zwrotów, przypisywania zasobów i przeglądania raportów.",
      "RoleLabel_Visitors": "Pracownik inwentarza",
      "RoleDesc_Visitors": "Dostęp tylko do odczytu dostępnych zapasów oraz uprawnienie do składania zgłoszeń zwrotu.",
      "ViewMembersButton": "Wyświetl członków",
      "LoadingButton": "Ładowanie...",
      "NoMembersFound": "Nie znaleziono członków w tej grupie",
      "SchemaTitle": "Wymagany schemat list",
      "SchemaDesc": "Kolumny, które musi zawierać każda lista. Po sprawdzeniu zielone kolumny znaleziono na liście, a czerwone są brakujące. Najedź na kolumnę, aby zobaczyć akceptowane nazwy alternatywne.",
      "SchemaAssetDatabase": "(Baza danych zasobów)",
      "SchemaApprovalWorkflows": "(Przepływy zatwierdzania)",
      "SchemaReturnsHandling": "(Obsługa zwrotów)",
      "SchemaCustodyTracking": "(Śledzenie posiadania)",
      "TabOverview": "Przegląd",
      "OverviewTitle": "Kondycja systemu",
      "LastChecked": "Ostatnie sprawdzenie: {0}",
      "NeverChecked": "Jeszcze nie sprawdzono",
      "RunHealthCheckButton": "Sprawdź kondycję",
      "RunningHealthCheck": "Sprawdzanie...",
      "ExportReportButton": "Eksportuj raport",
      "Tile_CoreLists": "Gotowe listy podstawowe",
      "Tile_SchemaIssues": "Brakujące kolumny",
      "Tile_PermissionIssues": "Listy bez prawa zapisu",
      "Tile_OptionalLists": "Znalezione listy opcjonalne",
      "IssuesTitle": "Wymagane działania",
      "ViewDetails": "Szczegóły",
      "NoIssues": "Wszystkie listy są połączone i mają oczekiwane kolumny oraz uprawnienia.",
      "EnvironmentTitle": "Środowisko",
      "Env_Site": "Witryna",
      "Env_User": "Zalogowano jako",
      "Env_SiteAdmin": "Administrator zbioru witryn",
      "Env_Language": "Język SharePoint",
      "Env_TotalLists": "Widoczne listy w witrynie",
      "Yes": "Tak",
      "No": "Nie",
      "Issue_Error": "{0}: {1}",
      "Issue_Missing": "{0}: nie znaleziono listy. Utwórz listę o nazwie \"{1}\" lub zmień nazwę istniejącej.",
      "Issue_AutoCreated": "{0}: jeszcze nie utworzono. Aplikacja utworzy ją automatycznie przy pierwszym użyciu.",
      "Issue_Columns": "{0}: brakujące kolumny ({1}): {2}",
      "Issue_Write": "{0}: Twoje konto nie może dodawać ani edytować elementów.",
      "StatusWarning": "Wymaga uwagi",
      "StatusMissing": "Nie znaleziono",
      "AccessReadWrite": "Odczyt i zapis",
      "AccessReadOnly": "Tylko odczyt",
      "AccessNone": "Brak dostępu",
      "OptionalBadge": "Opcjonalna",
      "AutoCreatedBadge": "Tworzona automatycznie",
      "Items": "Elementy:",
      "LastModified": "Ostatnia zmiana:",
      "Access": "Twój dostęp:",
      "Columns": "Kolumny:",
      "ColumnsSummary": "{0}/{1} obecnych",
      "ResponseTime": "Odpowiedź:",
      "OpenList": "Otwórz listę",
      "TriedNames": "Nazwy list wyszukiwane przez aplikację",
      "SimilarLists": "Podobne listy w tej witrynie",
      "RenameHint": "Jeśli jedna z nich jest właściwą listą, zmień jej nazwę na \"{0}\" w ustawieniach listy.",
      "MissingColumnsLabel": "Brakujące kolumny",
      "AllColumnsPresent": "Wszystkie wymagane kolumny są obecne.",
      "CoreListsGroup": "Listy podstawowe",
      "OptionalListsGroup": "Listy opcjonalne",
      "ListTitle_EventLogList": "Dziennik zdarzeń",
      "ListDesc_EventLogList": "Ścieżka audytu zmian zasobów, przejść cyklu życia i operacji administracyjnych. Wyświetlana w strumieniu zdarzeń.",
      "ListTitle_IncidentList": "Lista incydentów",
      "ListDesc_IncidentList": "Przechowuje zgłoszenia uszkodzeń, utraty i awarii zasobów.",
      "ListTitle_EmployeeList": "Lista pracowników",
      "ListDesc_EmployeeList": "Katalog pracowników używany do powiadomień i wyszukiwania incydentów.",
      "ListTitle_ReplacementList": "Wymiany zasobów",
      "ListDesc_ReplacementList": "Śledzi zasoby zastępcze wydane po incydentach.",
      "ListTitle_StockThresholdsList": "Progi zapasów",
      "ListDesc_StockThresholdsList": "Minimalny dostępny stan na typ zasobu dla alertów. Tworzona przy pierwszym zapisie progów.",
      "ListTitle_AssetKitsList": "Zestawy zasobów",
      "ListDesc_AssetKitsList": "Standardowe zestawy dla nowych pracowników. Tworzona przy pierwszym zapisie zestawu.",
      "ListTitle_AppSettingsList": "Ustawienia aplikacji inwentarza",
      "ListDesc_AppSettingsList": "Ustawienia aplikacji dla całej witryny, np. powiadomienia e-mail. Tworzona przy pierwszym zapisie ustawień.",
      "AccessUnknown": "Odczyt (zapis niezweryfikowany)",
      "ChecksLabel": "Co zostało sprawdzone",
      "CheckOptional": "opcjonalne",
      "Check_Find": "Znajdź listę po tytule",
      "Check_Columns": "Odczytaj kolumny listy",
      "Check_Items": "Odczytaj elementy",
      "Check_Permissions": "Odczytaj Twoje uprawnienia do listy",
      "Check_Details": "Odczytaj szczegóły listy (liczba elementów, ostatnia zmiana, link)",
      "Note_PermissionsFromSite": "Nie udało się odczytać Twoich uprawnień do listy, więc użyto uprawnień witryny. ({0})",
      "SchemaUnchecked": "Uruchom sprawdzenie, aby zweryfikować te kolumny na listach SharePoint.",
      "SchemaAliasesHint": "Akceptowane również: {0}",
      "SchemaAuditTrail": "(Ścieżka audytu)",
      "RbacRoleRule": "Każdy użytkownik otrzymuje najwyższą rolę spośród grup, do których należy.",
      "FilterMembersPlaceholder": "Filtruj członków...",
      "LoadAllGroupsButton": "Odśwież wszystko",
      "MemberCount": "Członkowie: {0}",
      "YouAreMember": "Jesteś członkiem",
      "GroupNotFound": "Ta grupa nie istnieje w witrynie, więc nikt nie może otrzymać tej roli, dopóki nie zostanie utworzona.",
      "GroupLoadError": "Nie można załadować członków: {0}",
      "OverviewSubtitle": "Sprawdza każdą listę SharePoint, kolumnę i uprawnienie, od których zależy aplikacja.",
      "OverallHealthy": "Wszystkie systemy działają",
      "OverallWarning": "Elementy wymagające uwagi: {0}",
      "OverallCritical": "Znalezione krytyczne problemy: {0}",
      "OverallHint": "Wybierz problem poniżej, aby przejść do danej listy."
    },

    "ReportsPage": {
      "HeaderTitle": "Raportowanie i statystyki",
      "HeaderSubtitle": "Aktualne dane o zasobach, gwarancjach, wnioskach i osobach. Wybierz liczbę lub wykres, aby zobaczyć szczegóły.",
      "TabVisualInsights": "Statystyki wizualne",
      "TabDetailedReports": "Szczegółowe raporty",
      "TabWarrantyExpiry": "Wygaśnięcie gwarancji",
      "StatTotalAssets": "CAŁKOWITA LICZBA ZASOBÓW INWENTARZA",
      "StatAssetsAssigned": "OBECNIE PRZYPISANE ZASOBY",
      "StatUtilizationRate": "WSKAŹNIK WYKORZYSTANIA",
      "StatTotalRequests": "CAŁKOWITA LICZBA WNIOSKÓW O ZATWIERDZENIE",
      "ChartStatusDistribution": "Rozkład statusu zasobów",
      "DataLabelInStock": "W magazynie",
      "DataLabelAssigned": "Przypisane",
      "DataLabelPendingReturn": "Oczekujący zwrot",
      "DataLabelUnderMaintenance": "W konserwacji",
      "LegendInStock": "W magazynie",
      "LegendAssigned": "Przypisane",
      "LegendPendingReturn": "Oczekujący zwrot",
      "LegendMaintenance": "Konserwacja",
      "ChartTypeDistribution": "Rozkład typu zasobów",
      "ChartDatasetAssetsCount": "Liczba zasobów",
      "ChartAgingAnalysis": "Analiza wieku zasobów",
      "DataLabelAgingUnder1": "< 1 rok (nowy)",
      "DataLabelAging1to3": "1-3 lata",
      "DataLabelAgingOver3": "> 3 lata (starzejący się)",
      "DataLabelAgingUnknown": "Nieznany",
      "LegendAgingUnder1": "< 1 rok",
      "LegendAging1to3": "1-3 lata",
      "LegendAgingOver3": "> 3 lata",
      "LegendAgingUnknown": "Nieznany",
      "ChartRequestTrends": "Trendy zatwierdzania wniosków",
      "DataLabelApproved": "Zatwierdzone",
      "DataLabelDeclinedRejected": "Odrzucone/Odmówione",
      "DataLabelPending": "Oczekujące",
      "DetailedTitle": "Filtrowalny inwentarz zasobów",
      "ExportExcel": "Eksportuj Excel",
      "ExportPDF": "Eksportuj PDF",
      "LabelAssetType": "Typ zasobu",
      "FilterAllTypes": "Wszystkie typy",
      "LabelAssetStatus": "Status zasobu",
      "FilterAllStatuses": "Wszystkie statusy",
      "ColUnassigned": "Nieprzypisane",
      "WarrantyTitle": "Raport wygaśnięcia gwarancji",
      "TotalAssetsCountLabel": "Całkowita liczba zasobów",
      "AssetsWithWarrantyLabel": "Zasoby z danymi gwarancyjnymi",
      "ColWarrantyExpiryDate": "Data wygaśnięcia gwarancji",
      "WarrantyNotAvailable": "Nie dotyczy",
      "WarrantyExpiredTag": "(Wygasła)",
      "WarrantyActiveTag": "(Aktywna)"
    },

    "InventoryPage": {
      "Title": "Przegląd bieżącego inwentarza",
      "Description": "Śledź i zarządzaj zasobami swojej organizacji w sposób efektywny w ramach SharePoint Framework.",
      "LoadingInventory": "Ładowanie inwentarza...",
      "ButtonAddNewAsset": "Dodaj nowy zasób",
      "ButtonAssignManageAssets": "Przypisz / Zarządzaj zasobami"
    },

    "IncidentHistoryPage": {
      "Title": "Historia incydentów"
    },

    "RequestAnalysis": {
      "OverviewTitle": "Przegląd wniosku",
      "LabelRequestKey": "Klucz wniosku:",
      "LabelRequestedAsset": "Żądany zasób:",
      "LabelQuantity": "Ilość:",
      "LabelPriority": "Priorytet:",
      "LabelRequesterName": "Nazwa wnioskodawcy:",
      "LabelEmployeeId": "ID pracownika:",
      "LabelRequestDate": "Data wniosku:",
      "LabelRequestStatus": "Status wniosku:",
      "LabelReasonForRequest": "Powód wniosku:",
      "LabelManagerResponse": "Odpowiedź menedżera:",
      "DetailedAnalysisTitle": "Szczegółowa analiza",
      "InventoryCheckLabel": "Kontrola dostępności zapasów:",
      "InventoryCheckPassedBold": "Kontrola zapasów zaliczona:",
      "InventoryCheckPassedBefore": "Obecnie dostępnych jest",
      "InventoryCheckPassedMiddle": "jednostek(-a)",
      "InventoryCheckPassedAfter": "w magazynie, co jest wystarczające do realizacji tego wniosku.",
      "InventoryWarningBold": "Ostrzeżenie o zapasach:",
      "InventoryWarningBefore": "Tylko",
      "InventoryWarningMiddle": "jednostek(-a)",
      "InventoryWarningAfter": "w magazynie. Wymagane jest zamówienie, aby w pełni zrealizować to zamówienie.",
      "StrategicRecommendationLabel": "Rekomendacja strategiczna:",
      "RecommendedActionBold": "Zalecana czynność:",
      "RecommendationApproveSufficient": "Zatwierdź wniosek. Dostępne są wystarczające zapasy, co umożliwia natychmiastowe przypisanie numeru seryjnego.",
      "RecommendationHoldBefore": "Wstrzymaj zatwierdzenie lub przypisz model alternatywny. Obecny zapas (",
      "RecommendationHoldAfter": ") jest niewystarczający. Zamów jednostki uzupełniające.",
      "RecommendationAssignBefore": "Przejdź do karty",
      "RecommendationAssignQueueLabel": "Kolejka przypisania zasobów",
      "RecommendationAssignMiddle": "aby przydzielić jeden z",
      "RecommendationAssignAfter": "dostępnych {0} dla {1}.",
      "LifecycleCompleteBold": "Cykl życia zakończony:",
      "LifecycleCompleteText": "Zasób został pomyślnie przydzielony. Nie jest wymagana dalsza czynność menedżera ani administratora.",
      "ClosedBold": "Zamknięte:",
      "ClosedText": "Wniosek został odrzucony. Zrealizuj alternatywne opcje lub przejrzyj argumenty w przypadku odwołania.",
      "LifecycleStageLabel": "Etap cyklu życia wniosku:",
      "StepSubmittedPending": "Złożony i oczekujący na zatwierdzenie",
      "StepManagerApproved": "Zatwierdzony przez menedżera - oczekuje na przypisanie zasobu",
      "StepCompleted": "Zakończony i zasób przypisany",
      "StepDeclined": "Odrzucony przez menedżera"
    },

    "AssetAnalysis": {
      "SpecificationsTitle": "Specyfikacje zasobu",
      "LabelAssetName": "Nazwa zasobu:",
      "LabelSerialNumber": "Numer seryjny:",
      "LabelAssetType": "Typ zasobu:",
      "LabelCurrentStatus": "Bieżący status:",
      "LabelCondition": "Stan:",
      "LabelVendor": "Dostawca:",
      "LabelPurchaseDate": "Data zakupu:",
      "LabelWarrantyExpiry": "Wygaśnięcie gwarancji:",
      "LabelAssetNotes": "Uwagi dotyczące zasobu:",
      "DetailedAnalysisTitle": "Analiza kondycji i amortyzacji",
      "LifecycleEolLabel": "Cykl życia zasobu i data końca eksploatacji:",
      "LifecyclePurchaseDatePrefix": "Data zakupu:",
      "LifecycleEolDatePrefix": "Firmowa data końca eksploatacji:",
      "WarrantyEvaluationLabel": "Ocena wygaśnięcia gwarancji:",
      "WarrantyExpiredBold": "Gwarancja wygasła:",
      "WarrantyExpiredBefore": "Ochrona zakończyła się",
      "WarrantyExpiredAfter": "Wszelkie przyszłe naprawy będą wiązać się z pełnymi bezpośrednimi kosztami biznesowymi.",
      "WarrantyExpiringSoonBold": "Gwarancja wkrótce wygaśnie (< 6 miesięcy):",
      "WarrantyExpiringSoonBefore": "Data wygaśnięcia to",
      "WarrantyExpiringSoonAfter": "Wysoki priorytet dla odnowienia sprzętu/gwarancji.",
      "WarrantyExpiring1YearBold": "Gwarancja wygasa (< 1 rok):",
      "WarrantyExpiring1YearBefore": "Data wygaśnięcia to",
      "WarrantyExpiring1YearAfter": "Zaplanuj nadchodzące zarządzanie cyklem życia sprzętu.",
      "WarrantyActiveBold": "Gwarancja aktywna (> 1 rok):",
      "WarrantyActiveBefore": "Pełna ochrona producenta do",
      "WarrantyActiveAfter": "",
      "WarrantyUnknownBold": "Gwarancja nieznana:",
      "WarrantyUnknownText": "Nie zarejestrowano daty wygaśnięcia gwarancji dla tego zasobu.",
      "PhysicalHealthLabel": "Stan fizyczny zasobu:",
      "HealthClassificationLabel": "Klasyfikacja kondycji:",
      "CriticalActionRecommendation": "Zalecenie krytycznej czynności: Zdecydowanie zaleca się wycofanie tego zasobu i złożenie wniosku o wymianę.",
      "HealthExcellent": "Doskonały",
      "HealthFair": "Dostateczny",
      "HealthCritical": "Krytyczny, wymaga wymiany"
    },

    "NotificationDetailsPanel": {
      "LabelReceived": "Otrzymano:",
      "SystemAlertTitle": "Analiza alertu systemowego",
      "GeneralNotificationText": "To jest ogólne powiadomienie systemowe. Nie ma bezpośredniego połączenia z bazą danych do aktywnego wniosku lub zasobu."
    },

    "AdminAssignmentPanel": {
      "RequestHeaderPrefix": "Wniosek #",
      "SubHeader": "Szczegóły wniosku o zasób",
      "RequestInfoTitle": "Informacje o wniosku",
      "BadgePendingAdmin": "Oczekuje na administratora",
      "LabelCategory": "Kategoria",
      "LabelQuantity": "Ilość",
      "LabelUrgency": "Pilność",
      "LabelSubmitted": "Złożono",
      "LabelJustification": "Uzasadnienie",
      "ApprovalTrailTitle": "Ścieżka zatwierdzania",
      "StepSubmitted": "Złożono",
      "StepManagerReview": "Weryfikacja menedżera",
      "ManagerReviewDefaultQuote": "Zatwierdzono - uzasadniona potrzeba biznesowa",
      "StepAdminAssignment": "Przypisanie przez administratora",
      "AwaitingAllocation": "Oczekuje na przydzielenie zasobu",
      "AdminAssignmentTitle": "Przypisanie przez administratora",
      "LabelAssignAssetOptional": "Przypisz zasób (opcjonalnie)",
      "PlaceholderSelectAsset": "Wybierz zasób do przypisania...",
      "PlaceholderNoAssetsInStock": "Brak zasobów tego typu w magazynie",
      "LabelComment": "Komentarz",
      "PlaceholderComment": "Dodaj komentarz wyjaśniający swoją decyzję...",
      "ButtonProcessing": "Przetwarzanie...",
      "ButtonAssignApprove": "Przypisz i zatwierdź",
      "ButtonReject": "Odrzuć"
    },

    "MyWorkspacePage": {
      "Title": "Moje miejsce pracy",
      "Description": "Zarządzaj przypisanymi zasobami i śledź swoje wnioski.",
      "TabsAriaLabel": "Karty Moje miejsce pracy",
      "TabAssets": "Zasoby",
      "ButtonRequestAsset": "Złóż wniosek o zasób",
      "TabRequests": "Wnioski"
    },

    "ApprovalsPage": {
      "Title": "Zatwierdzenia wniosków i kolejka przypisań",
      "Description": "Efektywnie śledź i zarządzaj wszystkimi wnioskami o zasoby.",
      "SearchLabel": "Szukaj według ID wniosku",
      "SearchPlaceholder": "np. REQ-000123",
      "ChartTitle": "Rozkład zatwierdzeń wniosków",
      "ChartDatasetLabel": "Wnioski według statusu",
      "NoDataLabel": "Brak danych"
    },

    "AssetAssignmentQueuePage": {
      "Title": "Zatwierdzone wnioski do przypisania zasobu",
      "Description": "Tutaj wyświetlane są tylko zatwierdzone wnioski, aby można było przypisać zasoby."
    },

    "AssetReturnsPage": {
      "Title": "Rejestr zwrotów zasobów",
      "Description": "Przeglądaj i finalizuj wnioski pracowników o zwrot zasobów oraz weryfikuj fizyczne zwroty sprzętu."
    },


    "MockEmailPanel": {
      "HeaderText": "📬 Powiadomienie o wychodzącej wiadomości e-mail (podgląd deweloperski)",
      "ButtonSending": "Wysyłanie...",
      "ButtonSendEmail": "Wyślij e-mail",
      "ButtonClose": "Zamknij",
      "InfoText": "Możesz przejrzeć, zmodyfikować odbiorcę(-ów) lub temat i wysłać tę wiadomość e-mail w celu przetestowania dostarczenia.",
      "LabelRecipients": "Odbiorcy (oddzieleni przecinkami)",
      "LabelSubject": "Temat",
      "SuccessText": "Wiadomość e-mail została pomyślnie wysłana do kolejki poczty Microsoft Graph / SharePoint!",
      "ErrorPrefix": "Nie udało się wysłać wiadomości e-mail:",
      "ProgressLabel": "Trwa transakcja wysyłki wiadomości e-mail...",
      "PreviewLabel": "Podgląd treści wiadomości e-mail:"
    },

    "IncidentSuccessPopup": {
      "Title": "Zgłoszenie incydentu zarejestrowane",
      "Stage": "Zarządzanie incydentami: Zarejestrowano",
      "Message": "Zgłoszenie incydentu dla \"{0}\" ({1}) zostało zarejestrowane i przypisane do wsparcia IT administratora.",
      "StatusOpenTicket": "Otwarte zgłoszenie"
    },

    "WarrantyUtils": {
      "NotAvailable": "Nie dotyczy",
      "NoWarrantyDate": "brak daty gwarancji",
      "InvalidDate": "nieprawidłowa data",
      "DaysAgoSingular": "{0} dzień temu",
      "DaysAgoPlural": "{0} dni temu",
      "DaysRemainingSingular": "pozostał {0} dzień",
      "DaysRemainingPlural": "pozostało {0} dni",
      "UnknownPurchaseDate": "Nieznana data zakupu",
      "InvalidPurchaseDate": "Nieprawidłowa data zakupu",
      "StatusEol": "Zasób osiągnął koniec cyklu życia (EOL)",
      "StatusActive": "Zasób znajduje się w aktywnym cyklu życia w przedsiębiorstwie"
    },

    "Columns": {
      "Id": "ID",
      "Title": "Tytuł",
      "AssetName": "Nazwa zasobu",
      "Type": "Typ",
      "SerialNumber": "Numer seryjny",
      "PurchaseDate": "Data zakupu",
      "Vendor": "Dostawca",
      "Condition": "Stan",
      "WarrantyExpiry": "Wygaśnięcie gwarancji",
      "Status": "Status",
      "AssignedTo": "Przypisano do",
      "Specifications": "Specyfikacja",
      "Actions": "Akcje",
      "ActivationState": "Stan aktywacji",
      "RequestId": "ID wniosku",
      "EmployeeName": "Imię i nazwisko pracownika",
      "ManagerName": "Imię i nazwisko kierownika",
      "AssetType": "Typ zasobu",
      "Priority": "Priorytet",
      "ManagerComment": "Komentarz kierownika",
      "AssetStatus": "Status zasobu",
      "AdminResponse": "Odpowiedź administratora",
      "RequestedDate": "Data wniosku",
      "Reason": "Powód",
      "ManagerNotes": "Uwagi kierownika"
    },

    "Pagination": {
      "ShowingEntries": "Wyświetlanie {0} do {1} z {2} pozycji",
      "FirstPage": "Pierwsza strona",
      "PreviousPage": "Poprzednia strona",
      "NextPage": "Następna strona",
      "LastPage": "Ostatnia strona"
    },

    "InventoryList": {
      "ActivationDeactivated": "Dezaktywowany",
      "ActivationActivated": "Aktywowany",
      "ActivationInactivated": "Nieaktywny",
      "ActionPendingReturn": "Oczekuje na zwrot",
      "ActionApproved": "Zatwierdzono",
      "ActionReturn": "Zwróć"
    },

    "EventStream": {
      "NoticeLabel": "Uwaga:",
      "ColumnAction": "Akcja",
      "ColumnUser": "Użytkownik",
      "ColumnTimestamp": "Znacznik czasu",
      "ColumnDetails": "Szczegóły",
      "LoadingAuditLogs": "Ładowanie dzienników zdarzeń...",
      "NoEventsForYou": "Nie zarejestrowano jeszcze żadnych zdarzeń audytu dla Ciebie.",
      "NoEventsRecorded": "Nie zarejestrowano jeszcze żadnych zdarzeń audytu.",
      "NoEventsMatchFilters": "Żadne zdarzenia audytu nie pasują do aktywnych filtrów.",
      "ActionCreated": "utworzono",
      "ActionManagerApproved": "zatwierdzone przez kierownika",
      "ActionManagerRejected": "odrzucone przez kierownika",
      "ActionAdminAssigned": "przydzielone przez administratora",
      "ActionInProgress": "status zmieniony na w toku",
      "ActionResolved": "status zmieniony na rozwiązane",
      "ActionDeleted": "usunięto",
      "ActionReturnRequested": "zgłoszono zwrot",
      "ActionReturnApproved": "zatwierdzono zwrot",
      "ActionReturnCompleted": "zakończono zwrot",
      "ActionReturnRejected": "odrzucono zwrot",
      "ActionActivated": "aktywowano",
      "ActionInactivated": "dezaktywowano",
      "ActionDeactivated": "wyłączono",
      "ActionUpdated": "zaktualizowano"
    },

    "EventFilters": {
      "SearchPlaceholder": "Szukaj według nazwy zasobu, tytułu, szczegółów, użytkownika lub akcji...",
      "LabelDateRange": "Zakres dat",
      "LabelAction": "Akcja",
      "LabelModule": "Moduł",
      "LabelAssetType": "Typ zasobu",
      "LabelUser": "Użytkownik",
      "LabelStatus": "Status",
      "LabelSortOrder": "Kolejność sortowania",
      "LabelStartDate": "Data początkowa",
      "LabelEndDate": "Data końcowa",
      "StartDatePlaceholder": "Wybierz datę początkową...",
      "EndDatePlaceholder": "Wybierz datę końcową...",
      "DateRangeWarning": "Ostrzeżenie: Data początkowa musi być wcześniejsza lub równa dacie końcowej.",
      "ActiveFilters": "Aktywne filtry:",
      "ClearAll": "Wyczyść wszystko",
      "ChipAction": "Akcja: {0}",
      "ChipModule": "Moduł: {0}",
      "ChipAsset": "Typ zasobu: {0}",
      "ChipUser": "Użytkownik: {0}",
      "ChipStatus": "Status: {0}",
      "AllActionsOption": "Wszystkie akcje",
      "AllAssetsOption": "Wszystkie typy zasobów",
      "AllUsersOption": "Wszyscy użytkownicy",
      "MyActivityOption": "Moja aktywność",
      "UserSearchPlaceholder": "Wpisz, aby wyszukać użytkowników..."
    },

    "RequestList": {
      "StatusPendingManagerApproval": "Oczekuje na zatwierdzenie przez kierownika",
      "ButtonReviewAssign": "Przejrzyj i przydziel",
      "NoAction": "Brak działania",
      "RejectionPrompt": "Podaj powód odrzucenia tego wniosku:",
      "AdminResponseWaitingOnManager": "Oczekuje na kierownika",
      "AdminResponseRejected": "Nie dotyczy (odrzucono)",
      "AdminResponseAllocated": "Zasób przydzielony",
      "AdminResponsePendingApproval": "Oczekuje na zatwierdzenie administratora",
      "EmptyState": "Nie znaleziono wniosków o zasoby.",
      "DetailsHeaderPrefix": "Szczegóły wniosku: {0}",
      "DetailsHeaderFallback": "Wniosek o zasób",
      "SectionRequestInformation": "Informacje o wniosku",
      "LabelRequestDate": "Data wniosku",
      "LabelAssetCategory": "Kategoria zasobu",
      "SectionJustification": "Uzasadnienie / Powód",
      "SectionManagerApproval": "Zatwierdzenie kierownika",
      "SectionAdminAllocation": "Przydział administratora",
      "AllocationAllocated": "Zasób przydzielony i wysłany ✓",
      "AllocationPendingAdmin": "Oczekuje na fizyczny przydział zasobu przez administratora systemu",
      "AllocationNotApplicable": "Nie dotyczy (wniosek został odrzucony przez kierownika)",
      "AllocationPendingManager": "Oczekuje najpierw na zatwierdzenie przez kierownika"
    },

    "ReturnRequestList": {
      "SearchPlaceholder": "Szukaj wniosków o zwrot...",
      "ColId": "ID",
      "ColEmployee": "Pracownik",
      "ColReason": "Powód",
      "EmptyState": "Nie znaleziono wniosków o zwrot.",
      "DialogTitleApprove": "Zatwierdź wniosek o zwrot",
      "DialogTitleReject": "Odrzuć wniosek o zwrot",
      "DialogTitleComplete": "Zweryfikuj i zakończ zwrot",
      "DialogTitleView": "Szczegóły wniosku o zwrot",
      "DialogSubtext": "Wniosek złożony przez {0} dotyczący zasobu {1}",
      "AlertRejectionRequired": "Podaj powód/komentarz odrzucenia.",
      "AlertVerificationRequired": "Podaj komentarz weryfikacyjny.",
      "AlertActionFailedPrefix": "Działanie nie powiodło się:",
      "CardTitle": "Szczegóły zwrotu zasobu",
      "LabelProposedCondition": "Proponowany stan",
      "LabelFinalCondition": "Ostateczny zweryfikowany stan",
      "LabelReturnReason": "Powód zwrotu",
      "LabelRejectionReason": "Powód odrzucenia (wymagane)",
      "LabelVerificationComments": "Komentarze weryfikacyjne (wymagane)",
      "LabelManagerComments": "Komentarze kierownika",
      "PlaceholderRejectionReason": "Podaj, dlaczego ten wniosek o zwrot jest odrzucany...",
      "PlaceholderVerificationComments": "Wprowadź szczegóły weryfikacji (wymagane)...",
      "PlaceholderManagerComments": "Dodaj komentarze do wniosku o zwrot...",
      "ButtonApprove": "Zatwierdź",
      "ButtonReject": "Odrzuć",
      "ButtonVerifyComplete": "Zweryfikuj i zakończ",
      "None": "Brak",
      "StatusPendingAdminVerification": "Oczekuje na weryfikację administratora",
      "LoadingReturnRequests": "Ładowanie wniosków o zwrot..."
    },

    "AssetHealth": {
      "MetricAssignedAssets": "Przydzielone zasoby",
      "MetricUnderWarranty": "Na gwarancji",
      "MetricWarrantyAction": "Działanie gwarancyjne",
      "MetricCriticalAlerts": "Alerty krytyczne",
      "SearchPlaceholder": "Szukaj według nazwy zasobu, typu, numeru seryjnego...",
      "AllTypesOption": "Wszystkie typy",
      "AllConditionsOption": "Wszystkie stany",
      "AllCoverageOption": "Wszystkie pokrycia",
      "WarrantyNoneRegistered": "brak daty gwarancji",
      "WarrantyInvalidDate": "Nieprawidłowa data",
      "WarrantyExpiringSoonDays": "Wkrótce wygasa ({0} dni)",
      "WarrantyActive": "Aktywna",
      "BadgeIssueActive": "Aktywne zgłoszenie",
      "BadgeReplacementRequested": "Wniosek o wymianę",
      "SerialNumberPrefix": "Nr seryjny:",
      "PurchasedPrefix": "Zakupiono:",
      "AgePrefix": "Wiek:",
      "AgeSuffix": "mies.",
      "RefreshEligible": "(Kwalifikuje się do wymiany ⚠️)",
      "WarrantyExpiredStrip": "Gwarancja wygasła:",
      "WarrantyExpiringStrip": "Gwarancja wygasa:",
      "WarrantyActiveStrip": "Gwarancja aktywna (wygasa: {0})",
      "ButtonDetails": "Szczegóły",
      "ButtonReportIssue": "Zgłoś problem",
      "ButtonAssetReplacement": "Wymiana zasobu",
      "ButtonPendingReturn": "Oczekuje na zwrot",
      "ButtonApprovedBadge": "Zatwierdzono",
      "ButtonReturn": "Zwróć",
      "EmptyStateTitle": "Nie znaleziono przydzielonych zasobów",
      "EmptyStateHint": "Spróbuj dostosować zapytanie wyszukiwania lub filtry.",
      "DetailsHeaderPrefix": "Szczegóły zasobu: {0}",
      "LabelAssetType": "Typ zasobu:",
      "LabelVendorBrand": "Dostawca/Marka:",
      "LabelSerialNumber": "Numer seryjny:",
      "LabelAssetStatus": "Status zasobu:",
      "LabelTitleDescription": "Opis tytułu:",
      "LifecycleReportTitle": "Raport cyklu życia i stanu",
      "LifecycleAgeLabel": "Wiek zasobu w cyklu życia",
      "LifecycleAgeText": "Ten zasób ma {0} mies. (lata: {1}). Standardowy cykl amortyzacji w przedsiębiorstwie to 36 miesięcy.",
      "LifecycleRefreshWarning": "⚠️ Zasób osiągnął/przekroczył standardowy 3-letni cykl życia. Kwalifikuje się do wymiany.",
      "LifecycleWithinLifecycle": "✓ Zasób mieści się w standardowym cyklu użytkowania (pozostało {0} mies.).",
      "LifecycleUnknownPurchaseDate": "Data zakupu nie została zarejestrowana. Nie można obliczyć wieku.",
      "WarrantyCoverageLabel": "Pokrycie gwarancyjne",
      "WarrantyExpiredMessage": "Gwarancja wygasła: Ochrona zakończyła się {0}. Przyszłe naprawy zostaną obciążone kosztami działu.",
      "WarrantyExpiringSoonMessage": "Gwarancja wkrótce wygasa: Wygasa {0}. Zaplanuj przegląd sprzętu przed wygaśnięciem.",
      "WarrantyActiveMessage": "Gwarancja aktywna: Pełna ochrona do {0}.",
      "WarrantyUnknownMessage": "Gwarancja nieznana: Brak zarejestrowanej daty wygaśnięcia gwarancji dla tej pozycji.",
      "PhysicalConditionLabel": "Stan fizyczny",
      "HealthRatingLabel": "Ocena stanu:",
      "RetireRecommendationTitle": "Zalecenie: WYCOFAJ ZASÓB",
      "RetireRecommendationText": "Ponieważ ten zasób jest w stanie {0}, zaleca się zwrot zasobu i złożenie wniosku o wymianę.",
      "SystemSpecificationsLabel": "Specyfikacja systemu",
      "ButtonReportIncident": "Zgłoś incydent",
      "ButtonRequestReturn": "Wniosek o zwrot",
      "HealthExcellent": "Doskonały",
      "HealthSatisfactory": "Zadowalający",
      "HealthDegraded": "Pogorszony",
      "HealthUnusable": "Nieużywalny / Zepsuty"
    },

    "MyRequests": {
      "PivotAriaLabel": "Moje wnioski",
      "TabAssetRequests": "Wnioski o zasoby",
      "TabReturnRequests": "Wnioski o zwrot",
      "MetricTotalRequests": "Wszystkie wnioski",
      "MetricPendingApproval": "Oczekuje na zatwierdzenie",
      "MetricApproved": "Zatwierdzone",
      "MetricDeclined": "Odrzucone",
      "AllPrioritiesOption": "Wszystkie priorytety",
      "SearchAssetRequestsPlaceholder": "Szukaj według ID wniosku, typu zasobu, powodu...",
      "SearchReturnRequestsPlaceholder": "Szukaj według nazwy zasobu, numeru seryjnego, powodu...",
      "RequestedPrefix": "Żądano: {0}",
      "QtyLabel": "Ilość",
      "ManagerLabel": "Kierownik:",
      "ManagerPrefix": "Kierownik: {0}",
      "ReasonPrefix": "Powód: {0}",
      "ManagerNoteLabel": "Uwaga kierownika:",
      "ManagerNotePrefix": "Uwaga kierownika: {0}",
      "WaitingOnManager": "Oczekuje na kierownika",
      "NotApplicableRejected": "Nie dotyczy (odrzucono)",
      "AssetAllocatedCheck": "Zasób przydzielony ✓",
      "PendingAdminAllocation": "Oczekuje na przydział administratora",
      "EmptyAssetRequestsTitle": "Nie znaleziono wniosków o zasoby",
      "EmptyFilterHint": "Spróbuj dostosować zapytanie wyszukiwania lub filtry.",
      "MetricTotal": "Razem",
      "MetricPending": "Oczekujące",
      "MetricCompleted": "Zakończone",
      "MetricRejected": "Odrzucone",
      "SubmittedPrefix": "Nr seryjny: {0} • Złożono: {1}",
      "ManagerNotesLabel": "Uwagi kierownika:",
      "AwaitingManagerReview": "Oczekuje na przegląd kierownika",
      "HandoverToItTeam": "Proszę fizycznie przekazać zasób zespołowi IT",
      "EmptyReturnRequestsTitle": "Nie znaleziono wniosków o zwrot",
      "EmptyReturnRequestsHint": "Nie złożono jeszcze żadnych wniosków o zwrot. Użyj przycisku „Zwróć” przy zasobie w sekcji Moje zasoby.",
      "DetailsHeaderPrefix": "Szczegóły wniosku: {0}",
      "FallbackAssetRequest": "Wniosek o zasób",
      "LabelRequestId": "ID wniosku:",
      "LabelDateRequested": "Data wniosku:",
      "LabelRequester": "Wnioskodawca:",
      "LabelEmployeeId": "Numer pracownika:",
      "LabelAssetType": "Typ zasobu:",
      "LabelQuantity": "Ilość:",
      "ReasonForRequestTitle": "Powód wniosku",
      "NoReasonProvided": "Nie podano powodu.",
      "ManagerApprovalStatusTitle": "Status zatwierdzenia przez kierownika",
      "AdminAllocationStatusTitle": "Status przydziału administratora",
      "ReturnRequestDetailsPrefix": "Wniosek o zwrot: {0}",
      "StatusPendingSubmitted": "Twój wniosek o zwrot został złożony i oczekuje na przegląd kierownika.",
      "StatusPendingAdminMsg": "Twój zwrot został zatwierdzony przez kierownika i oczekuje na ostateczną weryfikację przez administratora IT.",
      "StatusApprovedCompleted": "Twój zwrot został zatwierdzony i zakończony. Zasób został przyjęty.",
      "StatusRejectedMsg": "Twój wniosek o zwrot został odrzucony. Sprawdź uwagi kierownika poniżej.",
      "StatusCompletedMsg": "Zasób został pomyślnie przyjęty. Ten zwrot jest zakończony.",
      "LabelAssetName": "Nazwa zasobu:",
      "LabelSerialNumber": "Numer seryjny:",
      "LabelSubmittedOn": "Złożono:",
      "LabelProposedCondition": "Proponowany stan:",
      "LabelCompletedOn": "Zakończono:",
      "ReasonForReturnTitle": "Powód zwrotu",
      "NoReasonProvidedReturn": "Nie podano powodu.",
      "ProgressTitle": "Postęp procesu zwrotu",
      "ProgressSubmitted": "Zwrot złożony",
      "ProgressManagerReview": "Przegląd kierownika",
      "ProgressHandoverVerification": "Fizyczne przekazanie zasobu i weryfikacja administratora"
    },

    "IncidentHistory": {
      "SearchIncidentsPlaceholder": "Szukaj według ID zgłoszenia, nazwy zasobu lub typu problemu...",
      "SearchReplacementsPlaceholder": "Szukaj według ID wymiany, nazwy zasobu...",
      "FilterByStatusPlaceholder": "Filtruj według statusu",
      "AllStatusOption": "Wszystkie statusy",
      "ShowingIncidents": "Wyświetlanie {0} z {1} zgłoszeń",
      "ShowingReplacements": "Wyświetlanie {0} z {1} wniosków o wymianę",
      "ColIncidentId": "ID zgłoszenia",
      "ColReplacementId": "ID wymiany",
      "ColAsset": "Zasób",
      "ColIssueType": "Typ problemu",
      "ColType": "Typ",
      "ReplacementRequestType": "Wniosek o wymianę",
      "ColPriority": "Priorytet",
      "ColStatus": "Status",
      "ColReported": "Zgłoszono",
      "ColActions": "Akcje",
      "ButtonView": "Podgląd",
      "ButtonDownload": "Pobierz",
      "NoIncidentsFound": "Nie znaleziono zgłoszeń.",
      "NoReplacementsFound": "Nie znaleziono wniosków o wymianę.",
      "IncidentDetailsTitle": "Szczegóły zgłoszenia",
      "ReplacementDetailsTitle": "Szczegóły wniosku o wymianę",
      "ReportedLabel": "Zgłoszono:",
      "IncidentSpecificationsTitle": "Specyfikacja zgłoszenia",
      "ReplacementSpecificationsTitle": "Specyfikacja wymiany",
      "LabelIncidentId": "ID zgłoszenia:",
      "LabelReplacementId": "ID wymiany:",
      "LabelAssetName": "Nazwa zasobu:",
      "LabelIssueType": "Typ problemu:",
      "LabelType": "Typ:",
      "LabelPriority": "Priorytet:",
      "LabelStatus": "Status:",
      "LabelAssignedTo": "Przypisano do:",
      "UpdateResolutionTitle": "Aktualizuj szczegóły rozwiązania",
      "LabelResolvedDate": "Data rozwiązania:",
      "ResolutionSummaryLabel": "Podsumowanie rozwiązania",
      "ResolutionSummaryPlaceholderIncident": "Opisz, jak rozwiązano ten problem...",
      "ResolutionSummaryPlaceholderReplacement": "Opisz, jak zrealizowano tę wymianę...",
      "SaveResolutionButton": "Zapisz rozwiązanie",
      "ResolutionDetailsTitle": "Szczegóły rozwiązania",
      "ResolutionSummaryPrefix": "Podsumowanie rozwiązania:",
      "ToastIncidentUpdatedTitle": "Zgłoszenie zaktualizowane",
      "ToastStatusUpdatedTitle": "Status zaktualizowany",
      "ToastResolutionSavedTitle": "Rozwiązanie zapisane",
      "ToastStatusMessage": "Status zgłoszenia {0} zmieniono na „{1}”.",
      "ToastResolutionMessage": "Zapisano podsumowanie rozwiązania dla zgłoszenia {0}.",
      "PdfCompanyHeader": "MSFT ZARZĄDZANIE INWENTARZEM",
      "PdfIncidentReportTitle": "RAPORT ZGŁOSZENIA",
      "PdfReplacementReportTitle": "RAPORT WYMIANY ZASOBU",
      "PdfGeneratedOn": "Wygenerowano: {0}",
      "PdfIncidentSpecs": "SPECYFIKACJA ZGŁOSZENIA",
      "PdfReplacementSpecs": "SPECYFIKACJA WYMIANY",
      "PdfIncidentIdLabel": "ID zgłoszenia:",
      "PdfReplacementIdLabel": "ID wymiany:",
      "PdfAssetNameLabel": "Nazwa zasobu:",
      "PdfIssueTypeLabel": "Typ problemu:",
      "PdfTypeLabel": "Typ:",
      "PdfPriorityLabel": "Priorytet:",
      "PdfCurrentStatusLabel": "Aktualny status:",
      "PdfReportedDateLabel": "Data zgłoszenia:",
      "PdfAssignedToLabel": "Przypisano do:",
      "PdfResolvedDateLabel": "Data rozwiązania:",
      "PdfIssueDescriptionTitle": "OPIS PROBLEMU",
      "PdfReplacementReasonTitle": "POWÓD I SZCZEGÓŁY WYMIANY",
      "PdfNoDescription": "Nie podano opisu.",
      "PdfDownloadFailed": "Nie udało się utworzyć pliku PDF dla {0}. Spróbuj ponownie lub sprawdź konsolę przeglądarki.",
      "PdfDownloadFailedTitle": "Pobieranie nie powiodło się",
      "LocalOnlyTag": "Niezsynchronizowane",
      "LocalOnlyTooltip": "Zapisano tylko w tej przeglądarce, ponieważ SharePoint odrzucił zapis. Administratorzy nie widzą tego zgłoszenia.",
      "PdfNoReason": "Nie podano powodu.",
      "PdfResolutionSummaryTitle": "PODSUMOWANIE ROZWIĄZANIA"
    },
    "PropertyPaneConfig": {
      "DefaultPlaceholder": "Domyślnie: {0}",
      "NumberError": "Wprowadź liczbę równą 0 lub większą.",
      "GroupRoles": "Grupy ról",
      "RolesNote": "Grupy SharePoint nadające poszczególne role. Użytkownik otrzymuje najwyższą rolę spośród swoich grup. Pozostaw puste, aby użyć wartości domyślnej.",
      "AdminGroupLabel": "Grupa administratorów",
      "ManagerGroupLabel": "Grupa kierowników inwentarza",
      "EmployeeGroupLabel": "Grupa pracowników",
      "ListsPageDescription": "Listy SharePoint używane przez aplikację",
      "GroupLists": "Tytuły list",
      "ReloadNote": "Pozostaw puste, aby użyć domyślnego tytułu. Po zmianie tytułu odśwież stronę.",
      "InventoryListLabel": "Lista inwentarza",
      "RequestListLabel": "Lista wniosków",
      "ReturnRequestListLabel": "Lista wniosków o zwrot",
      "MappingListLabel": "Lista przypisań",
      "EventLogListLabel": "Lista dziennika zdarzeń",
      "IncidentListLabel": "Lista incydentów",
      "EmployeeListLabel": "Lista pracowników",
      "ReplacementListLabel": "Lista wymian zasobów",
      "StockThresholdsListLabel": "Lista progów zapasów",
      "AssetKitsListLabel": "Lista zestawów zasobów",
      "AppSettingsListLabel": "Lista ustawień aplikacji",
      "AlertsPageDescription": "Cele obsługi i alerty zapasów",
      "GroupSla": "SLA wniosków",
      "ApprovalSlaLabel": "Godziny na zatwierdzenie (cel)",
      "AssignmentSlaLabel": "Godziny na przypisanie po zatwierdzeniu (cel)",
      "GroupStock": "Alerty niskiego stanu",
      "DefaultMinimumLabel": "Domyślny minimalny stan na typ zasobu (0 = wył.)"
    },
    "Features": {
      "NavOnboarding": "Wdrażanie i odejścia",
      "Working": "Przetwarzanie...",
      "Cancel": "Anuluj",
      "DurationHours": "{0} godz.",
      "DurationDays": "{0} dni",
      "BatchPartial": "{0} powiodło się, {1} nie powiodło się: {2}",
      "SlaTitle": "SLA wniosków",
      "SlaSubtitle": "Cele: zatwierdzenie w {0} godz., przypisanie w {1} godz. od zatwierdzenia",
      "SlaOpenQueue": "Otwórz kolejkę",
      "SlaAvgApprove": "Średni czas zatwierdzenia",
      "SlaAvgAssign": "Średni czas przypisania",
      "SlaApprovedOnTime": "Zatwierdzone w terminie",
      "SlaOverdueBreakdown": "Po terminie ({0} zatw., {1} przyp.)",
      "SlaNoOverdue": "Żaden wniosek nie przekroczył terminu.",
      "SlaColRequest": "Wniosek",
      "SlaColAsset": "Zasób",
      "SlaColStage": "Etap",
      "SlaColWaiting": "Oczekuje",
      "SlaColOverBy": "Przekroczenie o",
      "SlaStageAwaitingApproval": "Oczekuje na zatwierdzenie",
      "SlaStageAwaitingAssignment": "Oczekuje na przypisanie",
      "SlaEstimatedHint": "Zatwierdzono przed rejestrowaniem dat decyzji; liczone od złożenia.",
      "SlaMoreOverdue": "+{0} więcej po terminie",
      "LowStockTitle": "Niski stan ({0})",
      "LowStockSubtitle": "Typy zasobów poniżej minimalnego dostępnego stanu",
      "LowStockManage": "Zarządzaj progami",
      "StockColType": "Typ zasobu",
      "StockColAvailable": "Dostępne",
      "StockColMinimum": "Minimum",
      "StockColTotal": "Łącznie",
      "StockColStatus": "Stan",
      "StockDefaultTag": "domyślne",
      "StockTabName": "Alerty zapasów",
      "StockTabTitle": "Progi niskiego stanu",
      "StockTabDesc": "Ustaw minimalną liczbę dostępnych sztuk na typ. Puste = domyślnie ({0}); 0 wyłącza monitorowanie. Administratorzy dostają jeden e-mail, gdy typ spadnie poniżej minimum, i kolejny dopiero po odbudowie i ponownym spadku.",
      "StockSave": "Zapisz progi",
      "StockCheckNow": "Sprawdź teraz",
      "StockSaved": "Progi zapisane.",
      "StockSaveFailed": "Nie można zapisać progów: {0}",
      "StockCheckFailed": "Sprawdzenie stanu nie powiodło się. Szczegóły w konsoli przeglądarki.",
      "StockAlertSent": "Wysłano alert dla: {0}",
      "StockNoNewAlerts": "Brak nowych alertów. Typy już zgłoszone nie są ponownie wysyłane do czasu odbudowy stanu.",
      "StockDefaultPlaceholder": "Domyślnie ({0})",
      "StockInvalid": "Wpisz 0 lub więcej",
      "StockMinimumAria": "Minimalny stan dla {0}",
      "StockNotMonitored": "Niemonitorowany",
      "StockLow": "Niski",
      "StockOk": "OK",
      "StockAlertedAt": "Alert wysłany {0}",
      "OnboardingPageTitle": "Wdrażanie i odejścia",
      "OnboardingPageSubtitle": "Zamów standardowy zestaw dla nowej osoby lub odzyskaj wszystkie zasoby od osoby odchodzącej.",
      "TabOnboarding": "Wdrażanie",
      "TabOffboarding": "Odejście",
      "TabKits": "Zestawy",
      "OnboardTitle": "Zamów zestaw startowy",
      "OnboardDesc": "Tworzy jeden wniosek na każdą pozycję zestawu. Każdy wniosek przechodzi zwykłe zatwierdzenie i przypisanie.",
      "OnboardEmployee": "Nowy pracownik",
      "OnboardEmployeePlaceholder": "Szukaj po nazwisku lub e-mailu...",
      "OnboardNoPeople": "Nie znaleziono osób",
      "OnboardEmployeeId": "ID pracownika (opcjonalnie)",
      "OnboardStartDate": "Data rozpoczęcia",
      "OnboardStartDatePlaceholder": "Wybierz datę...",
      "OnboardKit": "Zestaw",
      "KitOption": "{0} ({1} szt.)",
      "OnboardWillCreate": "Zostanie utworzonych wniosków: {0}.",
      "OnboardNotes": "Uwagi dla zatwierdzających (opcjonalnie)",
      "OnboardSubmit": "Zamów zestaw",
      "KitRequested": "Utworzono wniosków: {0}. Są teraz w kolejce do zatwierdzenia.",
      "OffboardTitle": "Lista kontrolna odejścia",
      "OffboardDesc": "Wybierz osobę odchodzącą, aby zobaczyć jej zasoby. Zgłoś zwroty jednym krokiem i śledź każdy do powrotu na stan.",
      "OffboardEmployee": "Odchodzący pracownik",
      "OffboardEmployeePlaceholder": "Wybierz osobę...",
      "OffboardNoHolders": "Nikt obecnie nie ma zasobów",
      "OffboardHolderOption": "{0} ({1} zasobów)",
      "OffboardLastDay": "Ostatni dzień pracy",
      "OffboardProgress": "Zwrócono {0} z {1} zasobów",
      "OffboardColSerial": "Numer seryjny",
      "OffboardStateHeld": "Nadal u pracownika",
      "OffboardStateInProgress": "Zwrot w toku",
      "OffboardStateReturned": "Zwrócono",
      "OffboardRaise": "Zgłoś zwroty dla {0} zasobów",
      "OffboardRaised": "Zgłoszono zwrotów: {0}. Przechodzą zwykłe zatwierdzenie zwrotu.",
      "OffboardNothingToRaise": "Każdy zasób ma już zwrot w toku.",
      "KitsTitle": "Zestawy startowe",
      "KitsDesc": "Zestawy są przechowywane na liście Zestawy zasobów.",
      "KitsBuiltInNote": "Wyświetlane są zestawy wbudowane. Zapisanie zestawu tworzy listę Zestawy zasobów; od tej chwili oferowane są tylko zestawy z listy.",
      "KitsCopyBuiltIn": "Zapisz wbudowane zestawy na liście",
      "KitsNew": "Nowy zestaw",
      "KitName": "Nazwa zestawu",
      "KitDescriptionLabel": "Opis",
      "KitItemsLabel": "Pozycje",
      "KitItemsHelp": "Jeden typ zasobu w wierszu. Ilość np. \"Monitor x2\".",
      "KitSave": "Zapisz zestaw",
      "KitSaved": "Zestaw zapisany.",
      "KitSaveFailed": "Nie można zapisać: {0}",
      "KitEdit": "Edytuj",
      "KitDelete": "Usuń",
      "KitDeleteConfirm": "Usunąć zestaw \"{0}\"?",
      "KitDeleted": "Zestaw usunięty."
    },
    "EmailCenter": {
      "Title": "Centrum poczty",
      "OpenButton": "E-mail",
      "OpenButtonAria": "Otwórz Centrum poczty",
      "OpenButtonFailedAria": "Otwórz Centrum poczty. Nieudane wiadomości: {0}.",
      "TabOutbox": "Skrzynka nadawcza",
      "TabSettings": "Ustawienia",
      "StatusOff": "Wysyłanie e-maili jest wyłączone. Wiadomości są tu widoczne, ale nie są wysyłane.",
      "StatusTestMode": "Tryb testowy jest włączony. E-maile o wnioskach, zatwierdzeniach, odrzuceniach i przydziałach trafiają do odbiorców testowych.",
      "OutboxEmpty": "Brak wiadomości w tej sesji. E-maile wysyłane przez aplikację pojawią się tutaj.",
      "OutboxSessionNote": "Pokazuje tylko wiadomości z tej sesji przeglądarki.",
      "ClearOutbox": "Wyczyść listę",
      "StatusSent": "Wysłano",
      "StatusFailed": "Niepowodzenie",
      "StatusSkipped": "Nie wysłano",
      "BackToOutbox": "Wszystkie wiadomości",
      "DetailSent": "Wysłano {0}.",
      "DetailSentFallback": "Wysłano {0} kanałem zapasowym SharePoint. Dostarczenie nie jest gwarantowane.",
      "DetailFailed": "Niepowodzenie {0}: {1}",
      "DetailSkipped": "Nie wysłano {0}, ponieważ wysyłanie e-maili jest wyłączone.",
      "SendNow": "Wyślij teraz",
      "SendAgain": "Wyślij ponownie",
      "SendBlockedOff": "Wysyłanie e-maili jest wyłączone. Włącz je w Ustawieniach, aby wysłać.",
      "ToLabel": "Do: {0}",
      "SectionDelivery": "Dostarczanie (dotyczy wszystkich)",
      "SectionDeliveryDesc": "Zapisywane na liście \"{0}\" w tej witrynie.",
      "ToggleEnabled": "Wysyłaj powiadomienia e-mail",
      "ToggleOn": "Wł.",
      "ToggleOff": "Wył.",
      "ToggleTestMode": "Tryb testowy",
      "TestModeDesc": "Wysyła e-maile o wnioskach, zatwierdzeniach, odrzuceniach i przydziałach do odbiorców testowych zamiast do właściwych osób. Alerty o niskim stanie zawsze trafiają do grupy administratorów.",
      "LabelTestAdminRecipients": "Odbiorcy testowi e-maili do administratorów i pracowników",
      "LabelTestManagerRecipient": "Odbiorca testowy e-maili do menedżerów",
      "RecipientsPlaceholder": "imie@firma.pl, imie2@firma.pl",
      "RecipientsRequired": "Wpisz co najmniej jeden prawidłowy adres e-mail.",
      "SaveSettings": "Zapisz ustawienia",
      "SettingsSaved": "Ustawienia poczty zapisane.",
      "SettingsSaveFailed": "Nie udało się zapisać ustawień: {0}",
      "SettingsLoading": "Wczytywanie ustawień...",
      "SectionBrowser": "W tej przeglądarce",
      "PreviewModeLabel": "Otwieraj Centrum poczty automatycznie",
      "PreviewModeNever": "Nigdy",
      "PreviewModeFailure": "Gdy wysyłka się nie powiedzie",
      "PreviewModeAlways": "Po każdej wiadomości",
      "StockAlertsHeld": "Niski stan dla {0}, ale alert nie został wysłany, ponieważ wysyłanie e-maili jest wyłączone w Centrum poczty."
    },
    "RejectDialog": {
      "Stage": "Przegląd menedżera",
      "Title": "Odrzuć wniosek {0}",
      "LabelEmployeeReason": "Uzasadnienie pracownika",
      "LabelCategory": "Powód odrzucenia",
      "CategoryPlaceholder": "Wybierz powód",
      "CategoryRequired": "Wybierz powód odrzucenia.",
      "CategoryNotJustified": "Potrzeba biznesowa nieuzasadniona",
      "CategoryBudget": "Budżet niezatwierdzony",
      "CategoryDuplicate": "Zduplikowany wniosek",
      "CategoryAlreadyHas": "Pracownik ma już ten zasób",
      "CategoryUnavailable": "Zasób niedostępny, poproś o alternatywę",
      "CategoryOther": "Inne",
      "LabelMessage": "Wiadomość do pracownika",
      "MessagePlaceholder": "Wyjaśnij decyzję i co pracownik może zrobić dalej.",
      "MessageRequired": "Napisz krótką wiadomość do pracownika.",
      "CharacterCount": "{0} / {1} znaków",
      "VisibilityNote": "Pracownik zobaczy ten powód w Moja przestrzeń → Wnioski. Menedżerowie widzą go w szczegółach wniosku.",
      "ConfirmButton": "Odrzuć wniosek",
      "Rejecting": "Odrzucanie...",
      "ReasonTitle": "Powód odrzucenia",
      "RejectedBy": "Odrzucił(a): {0}",
      "RejectedByOn": "Odrzucił(a): {0}, {1}"
    },
    "InventoryExplorer": {
      "StatusInStock": "Na stanie",
      "StatusAssigned": "Przydzielony",
      "StatusMaintenance": "W serwisie",
      "StatusPendingReturn": "Oczekuje na zwrot",
      "StatusRetired": "Wycofany",
      "StatusOther": "Inny status",
      "AgeUnderMonth": "Poniżej 1 miesiąca",
      "AgeMonths": "{0} mies.",
      "AgeYearsMonths": "{0} l. {1} mies.",
      "AgeYears": "{0} l.",
      "WarrantyNone": "Brak daty gwarancji",
      "WarrantyExpiredOn": "Gwarancja wygasła {0}",
      "WarrantyEndsInDays": "Gwarancja kończy się za {0} dni",
      "WarrantyUntil": "Gwarancja do {0}",
      "WarrantyExpiredShort": "Wygasła",
      "Uncategorised": "Bez kategorii",
      "CustodyAssigned": "Przydzielono {0}",
      "CustodyEmployeeId": "ID pracownika {0}",
      "CustodyReturn": "Zwrot: {0}",
      "CustodyCondition": "Stan: {0}",
      "SectionDetails": "Szczegóły",
      "FieldCategory": "Kategoria",
      "FieldType": "Typ",
      "FieldSerial": "Numer seryjny",
      "FieldVendor": "Dostawca",
      "FieldStatus": "Status",
      "FieldCondition": "Stan",
      "FieldPurchased": "Zakupiono",
      "FieldWarranty": "Gwarancja",
      "FieldAssignedTo": "Przydzielono do",
      "FieldAssetId": "ID zasobu",
      "SectionLifecycle": "Cykl życia",
      "LifecycleAge": "W użyciu od {0}",
      "LifecyclePlan": "Planowana wymiana po {0} latach",
      "SectionSpecifications": "Specyfikacja",
      "SectionNotes": "Notatki",
      "SectionCurrentHolder": "Obecny użytkownik",
      "NoCurrentHolder": "Obecnie nikomu nieprzydzielony.",
      "SectionCustody": "Historia użytkowania",
      "NoCustody": "Brak zarejestrowanych przydziałów lub zwrotów tego zasobu.",
      "NoActivity": "Brak zarejestrowanej aktywności dla tego zasobu.",
      "ActivityLimited": "Wyświetlono ostatnie {0} z {1} zdarzeń.",
      "NoServiceRecords": "Brak zgłoszeń i wniosków o wymianę dla tego zasobu.",
      "ServicePriority": "Priorytet: {0}",
      "SectionSharePoint": "Element SharePoint",
      "TechItemId": "ID elementu",
      "TechList": "Lista",
      "TechCreated": "Utworzono",
      "TechModified": "Ostatnia zmiana",
      "TechVersion": "Wersja",
      "TechLink": "Link",
      "OpenInSharePoint": "Otwórz w SharePoint",
      "SectionStoredValues": "Zapisane wartości",
      "IdLabel": "ID {0}",
      "ReturnInProgress": "Trwa zwrot tego zasobu.",
      "StatAge": "Wiek",
      "StatWarranty": "Pozostała gwarancja",
      "StatDays": "{0} dni",
      "StatHolders": "Użytkownicy",
      "StatOpenIssues": "Otwarte zgłoszenia",
      "TabOverview": "Przegląd",
      "TabPeople": "Osoby",
      "TabActivity": "Aktywność",
      "TabService": "Serwis",
      "TabTechnical": "Techniczne",
      "ColAsset": "Zasób",
      "Unnamed": "Zasób bez nazwy",
      "ColType": "Typ",
      "ColCategory": "Kategoria",
      "ColStatus": "Status",
      "ColAssignedTo": "Przydzielono do",
      "ColCondition": "Stan",
      "ColWarranty": "Gwarancja",
      "ColPurchased": "Zakupiono",
      "ColVendor": "Dostawca",
      "BreakdownItem": "{0} {1}",
      "TileTotal": "Wszystkie zasoby",
      "TileInStock": "Na stanie",
      "TileAssigned": "Przydzielone",
      "TileMaintenance": "W serwisie",
      "TileWarrantySoon": "Gwarancja kończy się w ciągu {0} dni",
      "AllTypes": "Wszystkie typy",
      "GroupByType": "Typ zasobu",
      "GroupByCategory": "Kategoria",
      "GroupByStatus": "Status",
      "GroupByNone": "Bez grupowania",
      "Subtitle": "Wszystkie zasoby w inwentarzu. Wybierz zasób, aby zobaczyć szczegóły, historię i zgłoszenia serwisowe.",
      "TilesAria": "Filtruj według statusu",
      "SearchPlaceholder": "Szukaj nazwy, numeru seryjnego, dostawcy lub osoby",
      "FilterType": "Typ",
      "GroupByLabel": "Grupuj według",
      "ResultCount": "{0} z {1} zasobów",
      "ExpandAll": "Rozwiń wszystko",
      "CollapseAll": "Zwiń wszystko",
      "ClearFilters": "Wyczyść filtry",
      "EmptyInventory": "Brak zasobów. Dodaj pierwszy, aby zacząć.",
      "EmptyFiltered": "Żaden zasób nie pasuje do filtrów.",
      "PageOf": "Strona {0} z {1}",
      "GroupPartial": "wiersze {0}–{1} z {2}"
    },
    "AssignmentQueue": {
      "Subtitle": "Wnioski zatwierdzone przez menedżera czekające na zasób. Wybierz wniosek, aby wybrać i przydzielić zasób.",
      "TilesAria": "Filtruj kolejkę",
      "TileWaiting": "Czekają na zasób",
      "TileWaitingHint": "Zatwierdzone, jeszcze nieprzydzielone",
      "TileReady": "Gotowe do przydzielenia",
      "TileReadyHint": "Wystarczający stan",
      "TileNoStock": "Za mały stan",
      "TileNoStockHint": "Wymaga zakupu lub zwrotu",
      "TileOverdue": "Po terminie",
      "TileOverdueHint": "Czekają ponad {0} godz.",
      "TileAssigned": "Przydzielone",
      "TileAssignedHint": "Już wydane",
      "SearchPlaceholder": "Szukaj ID wniosku, pracownika, zasobu lub menedżera",
      "FilterShow": "Pokaż",
      "ViewWaiting": "Oczekujące",
      "ViewAssigned": "Przydzielone",
      "ViewAll": "Wszystkie zatwierdzone",
      "FilterType": "Typ zasobu",
      "AllTypes": "Wszystkie typy",
      "GroupByLabel": "Grupuj według",
      "GroupByType": "Typ zasobu",
      "GroupByEmployee": "Pracownik",
      "GroupByPriority": "Priorytet",
      "GroupByNone": "Bez grupowania",
      "ResultCount": "{0} z {1} zatwierdzonych wniosków",
      "ExpandAll": "Rozwiń wszystko",
      "CollapseAll": "Zwiń wszystko",
      "ClearFilters": "Wyczyść filtry",
      "EmptyAllDone": "Nic nie czeka. Każdy zatwierdzony wniosek ma zasób.",
      "EmptyFiltered": "Żaden wniosek nie pasuje do filtrów.",
      "Unspecified": "Nie podano",
      "ColRequest": "Wniosek",
      "RequestedOn": "Złożono {0}",
      "ColEmployee": "Pracownik",
      "EmployeeId": "ID {0}",
      "ColAsset": "Zasób",
      "ColQuantity": "Ilość",
      "ColPriority": "Priorytet",
      "ColStock": "Stan",
      "InStockCount": "{0} na stanie",
      "PartialStock": "{0} z {1} na stanie",
      "OutOfStock": "Brak na stanie",
      "ColApprovedBy": "Zatwierdził(a)",
      "ColWaiting": "Czeka",
      "StatusAssigned": "Przydzielony",
      "OverdueBy": "Po terminie o {0}",
      "TargetHours": "Cel {0} godz.",
      "DurationUnderHour": "Poniżej 1 godz.",
      "DurationHours": "{0} godz.",
      "DurationDaysHours": "{0} dn. {1} godz.",
      "DurationDays": "{0} dn.",
      "Assign": "Przydziel",
      "Working": "Przetwarzanie...",
      "GroupWaiting": "{0} oczekuje",
      "GroupOverdue": "{0} po terminie",
      "GroupStock": "{0} na stanie",
      "PanelStockLine": "{0} × {1} na stanie dla wniosku o {2}. Najlepsze dopasowanie jako pierwsze.",
      "PanelNoStock": "Brak zasobu {0} na stanie. Nadal możesz zatwierdzić bez wyboru zasobu lub odrzucić wniosek.",
      "Recommended": "Zalecany"
    },
    "RecordLists": {
      "Today": "Dzisiaj",
      "Yesterday": "Wczoraj",
      "DaysAgo": "{0} dni temu",
      "MonthsAgo": "{0} mies. temu",
      "RangeAll": "Cały okres",
      "RangeLastDays": "Ostatnie {0} dni",
      "RangeThisYear": "Ten rok",
      "StatusOpen": "Otwarte",
      "StatusInProgress": "W toku",
      "StatusResolved": "Rozwiązane",
      "StatusClosed": "Zamknięte",
      "TileAll": "Wszystkie",
      "TileHighPriority": "Wysoki priorytet (aktywne)",
      "Unspecified": "Nie określono",
      "ColReportedBy": "Zgłaszający",
      "AllPriorities": "Wszystkie priorytety",
      "AllTypes": "Wszystkie typy",
      "AllPeople": "Wszyscy",
      "AllConditions": "Wszystkie stany",
      "ClearFilters": "Wyczyść filtry",
      "TilesAria": "Filtruj według statusu",
      "EmptyIncidents": "Nie zgłoszono jeszcze żadnych incydentów.",
      "EmptyReplacements": "Nie złożono jeszcze żadnych wniosków o wymianę.",
      "EmptyFiltered": "Nic nie pasuje do tych filtrów.",
      "SubtitleIncidents": "Śledź zgłoszone problemy z zasobami od zgłoszenia do rozwiązania. Wybierz kartę, aby zobaczyć szczegóły.",
      "SubtitleReplacements": "Śledź wnioski o wymianę od złożenia do rozwiązania. Wybierz kartę, aby zobaczyć szczegóły.",
      "ReturnNeedsMe": "Wymaga mojej akcji",
      "ReturnAwaitingManager": "Oczekuje na menedżera",
      "ReturnAwaitingAdmin": "Oczekuje na administratora",
      "ReturnCompleted": "Zakończone",
      "ReturnRejected": "Odrzucone",
      "ReturnNothingForMe": "Nic teraz nie czeka na Twoją akcję.",
      "ReturnShowAll": "Pokaż wszystkie wnioski o zwrot ({0})",
      "ReturnResultCount": "Wyświetlono {0} z {1} wniosków o zwrot",
      "ReturnCompletedOn": "Zakończono dnia",
      "ViewCards": "Karty",
      "ViewBoard": "Tablica",
      "ViewAria": "Układ",
      "SortLabel": "Sortuj według",
      "SortNewest": "Od najnowszych",
      "SortOldest": "Od najstarszych",
      "SortPriority": "Od najwyższego priorytetu",
      "SortAsset": "Nazwa zasobu (A–Z)",
      "SortEmployee": "Pracownik (A–Z)",
      "LaneEmpty": "Brak pozycji"
    },
    "Reports": {
      "TabRequests": "Wnioski",
      "TabPeople": "Osoby",
      "NoData": "Brak danych.",
      "KpiTotalAssets": "Wszystkie zasoby",
      "KpiTotalAssetsHint": "W {0} typach zasobów",
      "KpiInStock": "Na stanie",
      "KpiShareHint": "{0}% inwentarza",
      "KpiAssigned": "Przypisane",
      "KpiAssignedHint": "W posiadaniu {0} osób",
      "KpiUtilisation": "Wskaźnik wykorzystania",
      "KpiUtilisationHint": "{0} z {1} zasobów nie jest na stanie",
      "KpiOpenRequests": "Otwarte wnioski",
      "KpiOpenRequestsHint": "{0} czeka na zatwierdzenie · {1} czeka na przypisanie",
      "KpiWarranty": "Gwarancje do sprawdzenia",
      "KpiWarrantyHint": "{0} wygasło · {1} kończy się w ciągu 90 dni",
      "KpiLifecycle": "Po cyklu życia",
      "KpiLifecycleHint": "Starsze niż {0} lata",
      "KpiCondition": "Zły stan lub uszkodzone",
      "KpiConditionHint": "Wymagają naprawy lub wymiany",
      "SeriesOther": "Inne",
      "SeriesInProgress": "W toku",
      "ChartClickHint": "Wybierz segment, aby zobaczyć szczegóły",
      "ChartTypeSub": "Na stanie i przypisane, według typu",
      "ChartAgeSub": "Czas od zakupu",
      "ChartCondition": "Stan zasobów",
      "ChartRequestsMonthly": "Wnioski na miesiąc",
      "ChartRequestsMonthlySub": "Ostatnie 6 miesięcy, według wyniku",
      "ChartOutcomes": "Wyniki wniosków",
      "OutcomeAwaitingApproval": "Oczekuje na zatwierdzenie",
      "OutcomeAwaitingAssignment": "Oczekuje na przypisanie",
      "OutcomeFulfilled": "Zrealizowany",
      "OutcomeRejected": "Odrzucony",
      "WarrantyAttention": "Wymaga uwagi",
      "WarrantyExpired": "Wygasła",
      "WarrantyWithin30": "Kończy się w ciągu 30 dni",
      "WarrantyWithin90": "Kończy się za 31–90 dni",
      "WarrantyLater": "Ponad 90 dni",
      "WarrantyNoDate": "Brak daty gwarancji",
      "ChartWarrantyMonthly": "Gwarancje kończące się w miesiącu",
      "ChartWarrantyMonthlySub": "Następne 12 miesięcy",
      "ColAge": "Wiek",
      "ColReplaceBy": "Wymienić do",
      "SearchAssets": "Szukaj po nazwie, numerze seryjnym, typie lub osobie…",
      "LabelAssignment": "Przypisanie",
      "AssignmentAll": "Przypisane i nieprzypisane",
      "ResultAssets": "Wyświetlono {0} z {1} zasobów",
      "KpiRequests": "Wnioski",
      "KpiRequestsHint": "{0} nadal otwartych",
      "KpiApprovalRate": "Wskaźnik zatwierdzeń",
      "KpiApprovalRateHint": "{0} zatwierdzonych · {1} odrzuconych",
      "KpiAvgDecision": "Średni czas do decyzji",
      "KpiAvgDecisionHint": "Od wniosku do decyzji menedżera",
      "KpiAvgAssignment": "Średni czas do przypisania",
      "KpiAvgAssignmentHint": "Od zatwierdzenia do wydania",
      "ColAssetRequested": "Wnioskowany zasób",
      "ColOutcome": "Wynik",
      "ColDecisionTime": "Czas do decyzji",
      "ColEmail": "E-mail",
      "SearchRequests": "Szukaj po pracowniku, zasobie lub ID wniosku…",
      "LabelPeriod": "Okres",
      "ResultRequests": "Wyświetlono {0} z {1} wniosków",
      "TopRequested": "Najczęściej wnioskowane zasoby",
      "TopRequesters": "Najaktywniejsi wnioskodawcy",
      "TopSub": "W ramach powyższych filtrów. Wybierz wiersz, aby go wyszukać.",
      "KpiPeople": "Osoby z zasobami",
      "KpiPeopleHint": "Posiadają obecnie co najmniej jeden zasób",
      "KpiAssetsHeld": "Zasoby w posiadaniu",
      "KpiAssetsHeldHint": "Z łącznie {0} zasobów",
      "KpiAveragePerPerson": "Średnio na osobę",
      "KpiAveragePerPersonHint": "Zasoby na osobę posiadającą zasoby",
      "KpiLargestHolding": "Najwięcej zasobów",
      "ColAssignedOn": "Przypisano dnia",
      "SearchPeople": "Szukaj po osobie, zasobie lub numerze seryjnym…",
      "ResultPeople": "Wyświetlono {0} z {1} osób",
      "EmptyPeople": "Żadne zasoby nie są jeszcze przypisane.",
      "PeopleAssetCount": "Zasoby: {0}",
      "PdfAssetReportType": "Raport zasobów",
      "PdfWarrantyReportType": "Raport gwarancji",
      "PdfAssetHeading": "Inwentarz zasobów",
      "PdfAssetSubheading": "{0} zasobów w {1} typach",
      "PdfSummary": "Podsumowanie",
      "PdfAssetList": "Lista zasobów",
      "PdfEndingSoon": "Kończy się w ciągu 90 dni"
    },
    "EventFeed": {
      "Subtitle": "Oś czasu wszystkich zmian zasobów i wniosków. Wybierz zdarzenie, aby zobaczyć szczegóły.",
      "Refresh": "Odśwież",
      "StatEvents": "Zdarzenia w widoku",
      "StatToday": "Dzisiaj",
      "StatPeople": "Zaangażowane osoby",
      "ChartLast14": "Aktywność z ostatnich 14 dni",
      "BarTooltip": "{0}: {1} zdarzeń",
      "FiltersToggle": "Więcej filtrów",
      "FiltersToggleCount": "Więcej filtrów ({0})",
      "DayEvents": "Zdarzenia: {0}",
      "LabelReference": "ID rekordu",
      "ResultEvents": "Wyświetlono {0} z {1} zdarzeń"
    },
    "Approvals": {
      "Subtitle": "Przejrzyj każdy wniosek wraz ze stanem magazynu i zasobami pracownika, a następnie zatwierdź lub odrzuć.",
      "ChipToDecide": "Do decyzji",
      "SearchPlaceholder": "Szukaj po ID wniosku, pracowniku lub zasobie…",
      "SortWaiting": "Najdłużej oczekujące",
      "ListCount": "Wnioski: {0}",
      "AllCaughtUp": "Wszystko załatwione. Żaden wniosek nie czeka na Twoją decyzję.",
      "SelectPrompt": "Wybierz wniosek, aby go przejrzeć.",
      "StepRequested": "Złożono",
      "StepDecision": "Decyzja menedżera",
      "StepAssigned": "Zasób przypisany",
      "NoJustification": "Nie podano uzasadnienia.",
      "SectionStock": "Stan magazynu",
      "StockEnough": "{0} × {1} na stanie, wystarczy na ten wniosek o {2}.",
      "StockShort": "Tylko {0} × {1} na stanie dla wniosku o {2}. Zatwierdzenie jest zablokowane do czasu uzupełnienia magazynu.",
      "StockNone": "Brak {0} na stanie. Zatwierdzenie jest zablokowane do czasu uzupełnienia magazynu.",
      "ApproveBlocked": "Za mało na stanie, aby zatwierdzić ten wniosek.",
      "SectionEmployee": "O pracowniku",
      "HoldsNone": "Obecnie nie posiada żadnych zasobów.",
      "HoldsCount": "Obecnie posiadane zasoby: {0}",
      "HoldsSameType": "Posiada już {0} żądanego typu ({1}).",
      "DuplicateOpen": "Ma inny otwarty wniosek o {0}: {1}.",
      "OtherNone": "Brak innych wniosków tego pracownika.",
      "OtherRequests": "Inne wnioski: {0} ({1} nadal otwartych, {2} odrzuconych).",
      "SectionDecision": "Twoja decyzja",
      "CommentLabel": "Komentarz dla pracownika (opcjonalnie)",
      "CommentPlaceholder": "Dodaj notatkę do zatwierdzenia…"
    },
    "AccessGroups": {
      "AddMembers": "Dodaj członków",
      "AddMember": "Dodaj członka",
      "AddTitle": "Dodaj osoby do grupy",
      "LabelGroup": "Grupa",
      "LabelPeople": "Osoby",
      "PeoplePlaceholder": "Szukaj osób po nazwie lub e-mailu",
      "SuggestionsHeader": "Osoby w Twojej organizacji",
      "NoResults": "Nikt nie pasuje lub wszyscy znalezieni są już w tej grupie.",
      "Searching": "Wyszukiwanie…",
      "RoleHint": "Osoby otrzymują najwyższą rolę ze swoich grup, więc dodanie kogoś do {0} daje mu co najmniej rolę {1}.",
      "AddButton": "Dodaj do grupy",
      "Adding": "Dodawanie…",
      "AddedResult": "Dodano do {0}: {1}.",
      "AddFailed": "Nie udało się dodać {0}: {1}",
      "HideMembers": "Ukryj członków",
      "FilterMatches": "Dopasowania: {0}",
      "NoMatches": "Żaden członek nie pasuje do filtra.",
      "MembersOf": "Członkowie {0}"
    },
    "StockAlerts": {
      "TileMonitored": "Monitorowane typy",
      "TileMonitoredHint": "Z {0} typów zasobów",
      "TileBelow": "Poniżej minimum",
      "TileBelowNone": "Każdy monitorowany typ ma wystarczający zapas",
      "TileOut": "Brak na stanie",
      "TileOutHint": "Monitorowane typy bez dostępnych sztuk",
      "TileWaiting": "Sztuki oczekujące na przypisanie",
      "TileWaitingHint": "Zatwierdzone wnioski, które administrator musi jeszcze zrealizować",
      "ChipAttention": "Wymaga uwagi",
      "StatusOut": "Brak na stanie",
      "StatusRisk": "Zagrożony",
      "RiskNote": "Zatwierdzone wnioski obniżą stan poniżej minimum.",
      "Shortfall": "Brakuje {0} do minimum",
      "ColAssigned": "Przypisane",
      "ColWaiting": "Oczekujące wnioski",
      "ColAwaitingApproval": "Oczekuje na zatwierdzenie (szt.)",
      "ColAwaitingAssignment": "Oczekuje na przypisanie (szt.)",
      "ColAfter": "Po zatwierdzonych wnioskach",
      "AvailableOfTotal": "{0} z {1}",
      "WaitingAssignment": "{0} do przypisania",
      "WaitingApproval": "{0} oczekuje na zatwierdzenie",
      "SearchPlaceholder": "Szukaj typów zasobów…",
      "BulkLabel": "Minimum dla wszystkich typów na liście",
      "BulkApply": "Zastosuj",
      "ResetAlert": "Resetuj alert",
      "ResetAlertHint": "Wyślij alert ponownie przy następnym sprawdzeniu, jeśli stan nadal jest niski",
      "ResetDone": "Zresetowano alert dla {0}. Zostanie wysłany ponownie przy następnym sprawdzeniu, jeśli stan nadal będzie niski.",
      "Recipients": "Alerty o niskim stanie są wysyłane do {0}: {1}.",
      "NoRecipients": "Nikt w {0} nie ma adresu e-mail, więc alertów o niskim stanie nie można wysłać.",
      "EmailOff": "Poczta e-mail jest wyłączona w Centrum e-mail, więc alerty o niskim stanie są wstrzymane do czasu jej włączenia.",
      "CheckEmailFailed": "Niski stan: {0}. Nie udało się wysłać alertu e-mail: {1} Ponowna próba nastąpi przy następnym sprawdzeniu.",
      "CheckNoRecipients": "Niski stan: {0}, ale nikt w {1} nie ma adresu e-mail do powiadomienia."
    },
    "Maintenance": {
      "Title": "Konserwacja",
      "Subtitle": "Sprawdzaj dane pod kątem problemów, utrzymuj listę mapowań zgodną z przypisaniami i pobieraj kopie zapasowe.",
      "InventoryTitle": "Kontrola danych inwentarza",
      "InventoryDesc": "Wyszukuje zduplikowane lub brakujące numery seryjne, przypisania bez osoby, nieznane statusy oraz brakujące lub niemożliwe daty.",
      "RequestsTitle": "Kontrola kolejki wniosków",
      "RequestsDesc": "Wyszukuje wnioski po terminie SLA, zduplikowane otwarte wnioski, wnioski bez menedżera i wnioski o typy, których nie ma w inwentarzu.",
      "BackupTitle": "Kopie zapasowe",
      "BackupDesc": "Pobierz wszystkie wiersze listy jako plik CSV (otwiera się w Excelu), np. przed porządkowaniem.",
      "BackupInventory": "Inwentarz",
      "BackupRequests": "Wnioski",
      "BackupAudit": "Dziennik audytu",
      "BackupDone": "Pobrano wierszy: {0}.",
      "Preparing": "Przygotowywanie pliku…",
      "RunCheck": "Uruchom kontrolę",
      "RunAgain": "Uruchom ponownie",
      "Checking": "Sprawdzanie…",
      "CheckFailed": "Nie udało się przeprowadzić kontroli: {0}",
      "CheckedAt": "sprawdzono o {0}",
      "AssetsChecked": "Sprawdzone zasoby: {0}",
      "RequestsChecked": "Sprawdzone wnioski: {0}",
      "AllGood": "Nie znaleziono problemów.",
      "ExportFindings": "Eksportuj wyniki",
      "MoreRecords": "i {0} więcej (w eksporcie)",
      "ColCheck": "Kontrola",
      "ColRecord": "Rekord",
      "InvDuplicateSerial": "Zduplikowane numery seryjne",
      "InvDuplicateSerialHint": "Więcej niż jeden zasób ma ten sam numer seryjny.",
      "InvMissingSerial": "Brak numeru seryjnego",
      "InvMissingSerialHint": "Zwroty, mapowanie i zgłoszenia incydentów z niego korzystają.",
      "InvAssignedNoPerson": "Przypisany bez osoby",
      "InvAssignedNoPersonHint": "Status wskazuje przypisanie, ale nie zapisano osoby.",
      "InvPersonInStock": "Na stanie, ale zapisano osobę",
      "InvPersonInStockHint": "Zwykle pozostałość po zwrocie; usuń osobę lub popraw status.",
      "InvUnknownStatus": "Nierozpoznany status",
      "InvUnknownStatusHint": "Nie jest liczony jako na stanie ani przypisany w danych i raportach.",
      "InvMissingPurchase": "Brak daty zakupu",
      "InvMissingPurchaseHint": "Nie można ustalić wieku ani planu cyklu życia.",
      "InvMissingWarranty": "Brak daty gwarancji",
      "InvMissingWarrantyHint": "Pomijany w raportach i alertach gwarancyjnych.",
      "InvWarrantyBeforePurchase": "Gwarancja kończy się przed zakupem",
      "InvWarrantyBeforePurchaseHint": "Jedna z dwóch dat jest prawdopodobnie błędna.",
      "ReqOverdueApproval": "Zbyt długo czeka na menedżera",
      "ReqOverdueApprovalHint": "Przekroczono cel zatwierdzenia {0} h.",
      "ReqOverdueAssignment": "Zatwierdzony, ale nieprzypisany na czas",
      "ReqOverdueAssignmentHint": "Przekroczono cel przypisania {0} h.",
      "ReqDuplicates": "Zduplikowane otwarte wnioski",
      "ReqDuplicatesHint": "Ta sama osoba ma kilka otwartych wniosków o ten sam typ (złożonych przed regułą duplikatów).",
      "ReqNoManager": "Nie zapisano menedżera",
      "ReqNoManagerHint": "Oczekuje na zatwierdzenie, ale we wniosku nie wskazano menedżera.",
      "ReqUnknownType": "Typu nie ma w inwentarzu",
      "ReqUnknownTypeHint": "Nie ma zasobu żądanego typu, więc nie można go przypisać, dopóki nie zostanie dodany."
    }
  }
});
