define([], function() {
  return {
    "PropertyPaneDescription": "Ustawienia zarządzania inwentarzem",
    "BasicGroupName": "Ustawienia ogólne",
    "DescriptionFieldLabel": "Lokalizacja inwentarza",
    "AppLocalEnvironmentSharePoint": "Aplikacja działa w środowisku lokalnym jako składnik WebPart SharePoint",
    "AppLocalEnvironmentTeams": "Aplikacja działa w środowisku lokalnym jako aplikacja Microsoft Teams",
    "AppLocalEnvironmentOffice": "Aplikacja działa w środowisku lokalnym w witrynie office.com",
    "AppLocalEnvironmentOutlook": "Aplikacja działa w środowisku lokalnym w programie Outlook",
    "AppSharePointEnvironment": "Aplikacja działa na stronie SharePoint",
    "AppTeamsTabEnvironment": "Aplikacja działa w Microsoft Teams",
    "AppOfficeEnvironment": "Aplikacja działa w witrynie office.com",
    "AppOutlookEnvironment": "Aplikacja działa w programie Outlook",
    "UnknownEnvironment": "Aplikacja działa w nieznanym środowisku",

    "Common": {
      "Save": "Zapisz",
      "Cancel": "Anuluj",
      "Close": "Zamknij",
      "Submit": "Wyślij",
      "Approve": "Zatwierdź",
      "Reject": "Odrzuć",
      "View": "Podgląd",
      "ViewDetails": "Zobacz szczegóły",
      "Details": "Szczegóły",
      "Edit": "Edytuj",
      "Delete": "Usuń",
      "Add": "Dodaj",
      "Search": "Szukaj",
      "Loading": "Ładowanie...",
      "Processing": "Przetwarzanie...",
      "Reset": "Resetuj",
      "ResetFilters": "Resetuj",
      "ClearFilters": "Wyczyść filtry",
      "Actions": "Akcje",
      "Status": "Status",
      "Download": "Pobierz",
      "ExportExcel": "Eksportuj do Excela",
      "ExportPDF": "Eksportuj do PDF",
      "Yes": "Tak",
      "No": "Nie",
      "NotAvailable": "Nie dotyczy",
      "None": "Brak",
      "Unknown": "Nieznany",
      "All": "Wszystkie",
      "ErrorLabel": "Błąd:",
      "DismissError": "Odrzuć błąd",
      "LanguageLabel": "Język"
    },

    "Nav": {
      "Header": "Nawigacja",
      "RoleLabel": "Rola: {0}",
      "Dashboard": "Panel główny",
      "MyWorkspace": "Mój obszar roboczy",
      "Notifications": "Powiadomienia",
      "IncidentHistory": "Historia zgłoszeń",
      "ReplacementHistory": "Historia wymian",
      "Inventory": "Inwentarz",
      "Approvals": "Zatwierdzenia",
      "AssetAssignmentQueue": "Kolejka przydziału zasobów",
      "AssetReturns": "Zwroty zasobów",
      "EventStream": "Dziennik zdarzeń",
      "Users": "Użytkownicy",
      "Reports": "Raporty",
      "Config": "Konfiguracja",
      "GroupMain": "GŁÓWNE",
      "GroupManagement": "ZARZĄDZANIE",
      "GroupSystem": "SYSTEM",
      "Expand": "Rozwiń",
      "Collapse": "Zwiń",
      "ToggleNavigation": "Przełącz menu nawigacyjne",
      "MainNavigation": "Nawigacja główna"
    },

    "Roles": {
      "Admin": "Administrator",
      "InventoryManager": "Kierownik magazynu",
      "InventoryEmployee": "Pracownik magazynu"
    },

    "Hero": {
      "Title": "Zarządzanie inwentarzem",
      "WelcomeBack": "Witaj ponownie, {0}!",
      "RoleLabel": "Rola: {0}",
      "LocationLabel": "Lokalizacja: {0}",
      "SharePointGroupsLabel": "Grupy SharePoint: {0}"
    },

    "Dropdowns": {
      "AssetType": {
        "Laptop": "Laptop",
        "Monitor": "Monitor",
        "Mouse": "Mysz",
        "Keyboard": "Klawiatura",
        "Headset": "Zestaw słuchawkowy",
        "Other": "Inne"
      },
      "AssetCondition": {
        "New": "Nowy",
        "Excellent": "Doskonały",
        "Good": "Dobry",
        "Fair": "Zadowalający",
        "Poor": "Słaby",
        "Damaged": "Uszkodzony"
      },
      "IncidentType": {
        "HardwareIssue": "Problem sprzętowy",
        "SoftwareIssue": "Problem z oprogramowaniem",
        "NetworkIssue": "Problem z siecią",
        "AssetDamage": "Uszkodzenie zasobu",
        "ReplacementRequest": "Wniosek o wymianę",
        "AccessIssue": "Problem z dostępem",
        "LoginIssue": "Problem z logowaniem",
        "PerformanceIssue": "Problem z wydajnością",
        "EmailIssue": "Problem z pocztą e-mail",
        "PrinterIssue": "Problem z drukarką",
        "Other": "Inne"
      },
      "IncidentPriority": {
        "Low": "Niski",
        "Medium": "Średni",
        "High": "Wysoki",
        "Critical": "Krytyczny"
      },
      "IncidentStatus": {
        "Open": "Otwarte",
        "InProgress": "W toku",
        "Resolved": "Rozwiązane",
        "Closed": "Zamknięte"
      },
      "ReturnCondition": {
        "Good": "Dobry (brak uszkodzeń, w pełni sprawny)",
        "Fair": "Zadowalający (niewielkie zużycie, w pełni sprawny)",
        "Poor": "Słaby (znaczne zużycie, wymaga naprawy)",
        "Damaged": "Uszkodzony (zepsuty, niesprawny)"
      },
      "ReturnRequestStatus": {
        "Pending": "Oczekujące",
        "Approved": "Zatwierdzone",
        "Rejected": "Odrzucone",
        "Completed": "Zakończone"
      },
      "AssetRequestPriority": {
        "Low": "Niski",
        "Medium": "Średni",
        "High": "Wysoki"
      },
      "AssetRequestStatus": {
        "PendingManagerApproval": "Oczekuje na zatwierdzenie przez kierownika",
        "ApprovedByManager": "Zatwierdzone przez kierownika",
        "Rejected": "Odrzucone",
        "AssetAssigned": "Zasób przydzielony"
      },
      "WarrantyStatus": {
        "Active": "Aktywna",
        "ExpiringSoon": "Wkrótce wygasa",
        "Expired": "Wygasła",
        "Unknown": "Nieznana"
      },
      "AuditLogDateRange": {
        "All": "Cały czas",
        "Today": "Dzisiaj",
        "Yesterday": "Wczoraj",
        "Last7": "Ostatnie 7 dni",
        "Last15": "Ostatnie 15 dni",
        "Last30": "Ostatnie 30 dni",
        "Last60": "Ostatnie 60 dni",
        "Last90": "Ostatnie 90 dni",
        "ThisWeek": "Ten tydzień",
        "ThisMonth": "Ten miesiąc",
        "Custom": "Niestandardowy zakres dat"
      },
      "AuditLogModule": {
        "All": "Wszystkie moduły",
        "Inventory": "Inwentarz",
        "Requests": "Wnioski",
        "Returns": "Zwroty",
        "Users": "Użytkownicy",
        "Reports": "Raporty",
        "Configuration": "Konfiguracja",
        "Notifications": "Powiadomienia"
      },
      "AuditLogStatus": {
        "All": "Wszystkie statusy",
        "Pending": "Oczekujące",
        "Approved": "Zatwierdzone",
        "Rejected": "Odrzucone",
        "Assigned": "Przydzielone",
        "Returned": "Zwrócone",
        "Completed": "Zakończone"
      },
      "AuditLogSort": {
        "NewestFirst": "Od najnowszych",
        "OldestFirst": "Od najstarszych",
        "AssetNameAZ": "Nazwa zasobu A-Z",
        "AssetNameZA": "Nazwa zasobu Z-A",
        "UserAZ": "Użytkownik A-Z",
        "UserZA": "Użytkownik Z-A"
      },
      "IncidentRaisedTo": {
        "Admin": "Administrator"
      }
    },

    "Lifecycle": {
      "RequestAsset": "Wniosek o zasób IT",
      "Acquisition": "Zakup zasobu",
      "Deployment": "Wdrożenie i przydział",
      "Support": "Bieżące wsparcie i konserwacja",
      "EndOfLife": "Koniec eksploatacji i utylizacja",
      "BadgeTitle": "Zasób IT",
      "BadgeSubtitle": "Cykl życia"
    },

    "Dashboard": {
      "AdminTitle": "Panel administratora",
      "ManagerTitle": "Panel kierownika",
      "EmployeeTitle": "Mój panel",
      "RoleAdministrator": "Administrator",
      "RoleManager": "Kierownik magazynu",
      "RoleEmployee": "Pracownik",
      "OverviewSuffix": "Przegląd",
      "RealTimeAnalytics": "Analizy w czasie rzeczywistym",
      "ActionViewInventory": "Zobacz inwentarz",
      "ActionAssignmentQueue": "Kolejka przydziału",
      "ActionReports": "Raporty",
      "ActionEventStream": "Dziennik zdarzeń",
      "ActionReviewApprovals": "Przejrzyj zatwierdzenia",
      "ActionAssetReturns": "Zwroty zasobów",
      "ActionMyWorkspace": "Mój obszar roboczy",
      "ActionNotifications": "Zobacz powiadomienia",
      "ManagerBannerTitle": "Panel kierownika magazynu",
      "ManagerBannerTextBefore": "— Wskaźniki wizualne i kolejki zatwierdzeń są agregowane na podstawie list wniosków. Pełne dane znajdują się w rejestrze ",
      "ManagerBannerTextAfter": ".",
      "AdminBannerTitle": "Panel administratora",
      "AdminBannerText": "— Analizy pochodzą bezpośrednio z fizycznych pozycji inwentarza. Wskaźniki przydziału pokazują pozycje zatwierdzone przez administratora.",
      "EmployeeBannerTitle": "Centrum zasobów osobistych",
      "EmployeeBannerText": "— Telemetria w czasie rzeczywistym śledząca przydzielone urządzenia i status bieżących wniosków.",
      "TotalAssets": "Wszystkie zasoby",
      "MyDevices": "Moje urządzenia",
      "AllocationRateSubtitle": "Wskaźnik przydziału: {0}% przydzielone",
      "AssignedHardwareSubtitle": "{0} przydzielonych urządzeń",
      "ItemsInCatalogSubtitle": "{0} pozycji w katalogu",
      "AvailableAssets": "Dostępne zasoby",
      "InStockSubtitle": "{0} w magazynie ({1}% całości)",
      "RequestsInQueue": "Wnioski w kolejce",
      "MyRequests": "Moje wnioski",
      "TotalRequests": "Wszystkie wnioski",
      "QueueRequestsSubtitle": "{0} wniosków w kolejce",
      "ApprovalSuccessSubtitle": "Skuteczność zatwierdzeń: {0}%",
      "AwaitingApproval": "Oczekuje na zatwierdzenie",
      "PendingRequests": "Oczekujące wnioski",
      "RequiresReviewSubtitle": "{0} wymaga przeglądu",
      "UnderReviewSubtitle": "{0} w trakcie przeglądu przydziału",
      "RequestsInApprovalQueueLabel": "Wnioski w kolejce zatwierdzeń",
      "AssetsByStatusLabel": "Zasoby według statusu",
      "NoDataLabel": "Brak danych",
      "NoAssetsLabel": "Brak zasobów",
      "NumberOfAssetsLabel": "Liczba zasobów",
      "NoApprovedRequestsYetLabel": "Brak jeszcze zatwierdzonych wniosków",
      "AssignmentStatusApprovedLabel": "Status przydziału (wnioski zatwierdzone)",
      "RequestsByStatusLabel": "Wnioski według statusu",
      "KpiRegionAriaLabel": "Kluczowe wskaźniki wydajności",
      "ApprovalsQueueStatusTitle": "Status kolejki zatwierdzeń",
      "ApprovalsQueueStatusSubtitle": "Wnioski pogrupowane według stanu zatwierdzenia przez kierownika",
      "AssetStatusDistributionTitle": "Rozkład statusów zasobów",
      "AssetStatusDistributionSubtitle": "Aktualny stan i status zarejestrowanych zasobów",
      "AssetsByTypeTitle": "Zasoby według typu",
      "AssetsByTypeSubtitle": "Rozkład kategorii sprzętu",
      "PostApprovalAssignmentTitle": "Status przydziału po zatwierdzeniu",
      "RequestFulfillmentTitle": "Status realizacji wniosków",
      "PostApprovalAssignmentSubtitle": "Status wydania zasobów dla wniosków zatwierdzonych przez kierownika",
      "RequestFulfillmentSubtitle": "Aktualny status we wszystkich procesach wniosków",
      "AdminActionCenterTitle": "Centrum działań — przydział zasobów",
      "AdminActionCenterSubtitle": "Ostatnie wnioski zatwierdzone przez kierownika oczekujące na fizyczne wydanie sprzętu przez administratorów",
      "ColRequester": "Wnioskodawca",
      "ColAssetRequested": "Żądany zasób",
      "ColQty": "Ilość",
      "ColDateApproved": "Data zatwierdzenia",
      "ColStatusAction": "Działanie statusu",
      "BadgeAwaitingHandoff": "Oczekuje na wydanie",
      "AdminEmptyState": "Wszystkie przydziały zrealizowane! Brak oczekujących wydań sprzętu.",
      "AdminEmptyStateHint": "Sprawdź kolejkę przydziału, aby zobaczyć dane historyczne",
      "ManagerActionCenterTitle": "Oczekujące decyzje kierownika",
      "ManagerActionCenterSubtitle": "Ostatnie wnioski pracowników oczekujące na Twoje zatwierdzenie lub odrzucenie",
      "ColDateRequested": "Data wniosku",
      "ColReason": "Powód / Uzasadnienie",
      "NoJustificationSpecified": "Nie podano uzasadnienia",
      "ColActionState": "Stan działania",
      "BadgeAwaitingApproval": "Oczekuje na zatwierdzenie",
      "ManagerEmptyState": "Brak oczekujących wniosków! Twoja kolejka zatwierdzeń jest pusta.",
      "ManagerEmptyStateHint": "Nowe wnioski pojawią się tutaj automatycznie",
      "EmployeeActionCenterTitle": "Status aktywnych wniosków",
      "EmployeeActionCenterSubtitle": "Ostatnie wnioski o sprzęt w trakcie weryfikacji",
      "ColAsset": "Zasób",
      "ColManagerName": "Imię i nazwisko kierownika",
      "ColManagerComment": "Komentarz kierownika",
      "ColFulfillmentState": "Stan realizacji",
      "BadgeAwaitingReview": "Oczekuje na przegląd",
      "BadgeCompletedAssigned": "Zakończone i przydzielone",
      "BadgeApprovedAwaitingHandoff": "Zatwierdzone, oczekuje na wydanie",
      "BadgeDeclined": "Odrzucone",
      "EmployeeEmptyState": "Brak ostatnio złożonych aktywnych wniosków.",
      "EmployeeEmptyStateHint": "Użyj opcji „Wniosek o zasób”, aby złożyć nowy wniosek",
      "MyEquipmentTitle": "Mój przydzielony sprzęt",
      "MyEquipmentSubtitle": "Sprzęt aktualnie zarejestrowany i przydzielony Tobie",
      "ColDeviceName": "Nazwa urządzenia",
      "ColCategory": "Kategoria",
      "ColSerialNumber": "Numer seryjny",
      "ColAssignedDate": "Data przydziału",
      "MyEquipmentEmptyState": "Obecnie nie masz przydzielonego żadnego sprzętu.",
      "MyEquipmentEmptyStateHint": "Przydzielone urządzenia pojawią się tutaj po wydaniu"
    },

    "WorkflowPopup": {
      "GotIt": "Rozumiem",
      "LabelRequestId": "ID wniosku",
      "LabelReplacementId": "ID wymiany",
      "LabelIncidentId": "ID zgłoszenia",
      "LabelAsset": "Zasób",
      "LabelRequester": "Wnioskodawca",
      "LabelManagerName": "Imię i nazwisko kierownika",
      "LabelWorkflowStatus": "Status procesu",
      "LabelDate": "Data",
      "LabelCondition": "Stan",
      "LabelManagerAdminNotes": "Uwagi kierownika / administratora"
    },

    "Notifications": {
      "FilterAriaLabel": "Filtruj powiadomienia",
      "TabAll": "Wszystkie",
      "TabRequests": "Wnioski",
      "TabAssignments": "Przydziały",
      "TabSystemAlerts": "Alerty systemowe",
      "MarkAllAsRead": "Oznacz wszystkie jako przeczytane",
      "ClearFiltered": "Wyczyść przefiltrowane",
      "AllCaughtUpTitle": "Wszystko na bieżąco!",
      "EmptyStateMessage": "Nie znaleziono powiadomień w kategorii „{0}”.",
      "CategoryAll": "Wszystkie",
      "CategoryRequests": "Wnioski",
      "CategoryAssignments": "Przydziały",
      "CategoryAudits": "Audyty",
      "ViewDetails": "Zobacz szczegóły",
      "MarkAsRead": "Oznacz jako przeczytane",
      "DismissNotification": "Odrzuć powiadomienie"
    },

    "AssetForm": {
      "HeaderAdmin": "Dodaj nowy zasób",
      "HeaderManager": "Zarejestruj nowy zasób",
      "ManagerHint": "Rejestrujesz nowy zasób. Po dodaniu możesz przydzielić go pracownikom w sekcji Śledzenie zasobów.",
      "LabelTitle": "Tytuł (Grupa/Kategoria)",
      "LabelAssetName": "Nazwa zasobu",
      "LabelAssetType": "Typ zasobu",
      "LabelSerialNumber": "Numer seryjny",
      "LabelPurchaseDate": "Data zakupu",
      "LabelVendor": "Dostawca",
      "VendorPlaceholder": "Np. Dell, Apple, Microsoft, Lenovo",
      "LabelCondition": "Stan",
      "LabelWarrantyExpiry": "Data wygaśnięcia gwarancji",
      "LabelSpecifications": "Specyfikacja",
      "SpecificationsPlaceholder": "Np. Intel i7, 16GB RAM, 512GB SSD, itp.",
      "AddAsset": "Dodaj zasób"
    },

    "RequestForm": {
      "HeaderText": "Wniosek o zasób",
      "OnBehalfHint": "Wnioskujesz o ten zasób dla siebie. Składanie wniosków w imieniu innych użytkowników jest wyłączone.",
      "LabelRequester": "Wnioskodawca",
      "LabelEmployeeId": "Numer pracownika",
      "LabelManagerName": "Imię i nazwisko kierownika",
      "ManagerNamePlaceholder": "Wpisz imię i nazwisko kierownika",
      "ManagerNameRequired": "Imię i nazwisko kierownika jest wymagane",
      "LabelRequestedDate": "Data wniosku",
      "LabelAssetType": "Typ zasobu",
      "LabelPriority": "Priorytet",
      "LabelQuantity": "Ilość",
      "LabelReason": "Powód wniosku",
      "ReasonRequired": "Powód wniosku jest wymagany",
      "SubmitRequest": "Wyślij wniosek"
    },

    "ReturnAssetForm": {
      "HeaderText": "Wniosek o zwrot zasobu",
      "AssetInfoTitle": "Informacje o zasobie",
      "LabelAssetName": "Nazwa zasobu",
      "LabelSerialNumber": "Numer seryjny",
      "LabelType": "Typ",
      "LabelCurrentCondition": "Obecny stan",
      "LabelReturnedCondition": "Stan zwracanego zasobu",
      "LabelReturnReason": "Powód zwrotu",
      "ReturnReasonPlaceholder": "Opisz, dlaczego zwracasz ten zasób (np. otrzymano nowszy model, awaria sprzętu, zakończenie umowy...)",
      "ReturnReasonRequired": "Powód jest wymagany",
      "SubmitRequest": "Wyślij wniosek",
      "ErrorPrefix": "Błąd:",
      "GenericSubmitError": "Nie udało się złożyć wniosku o zwrot."
    },

    "IncidentRequestModule": {
      "HeaderReplacement": "Wniosek o wymianę zasobu",
      "HeaderIncident": "Zgłoś incydent",
      "NoAssetsReplacementInfo": "Obecnie nie masz przypisanych zasobów, dla których można złożyć wniosek o wymianę.",
      "NoAssetsIncidentInfo": "Obecnie nie masz przypisanych zasobów. Nadal możesz zgłaszać ogólne incydenty.",
      "LabelEmployeeName": "Imię i nazwisko pracownika",
      "LabelSelectAsset": "Wybierz przypisany zasób",
      "PlaceholderLoadingAssets": "Ładowanie zasobów...",
      "PlaceholderChooseAsset": "Wybierz jeden z przypisanych zasobów",
      "LabelAssetName": "Nazwa zasobu",
      "LabelSerialNo": "Numer seryjny",
      "LabelIssueType": "Typ problemu",
      "PlaceholderIssueType": "Wybierz typ problemu",
      "LabelPriority": "Priorytet",
      "LabelReasonForReplacement": "Powód wymiany",
      "LabelDescription": "Opis",
      "PlaceholderReasonForReplacement": "Opisz powód wymiany...",
      "PlaceholderDescribeIssue": "Opisz problem...",
      "LabelRaisedTo": "Zgłoszono do",
      "PlaceholderSelectTeam": "Wybierz zespół",
      "LabelRaisedDate": "Data zgłoszenia",
      "LabelStatus": "Status",
      "RequestReplacement": "Wniosek o wymianę",
      "ReportIncident": "Zgłoś incydent",
      "Cancel": "Anuluj",
      "ValidationRequiredFields": "Proszę wypełnić wszystkie wymagane pola.",
      "ErrorPrefix": "Błąd:",
      "GenericSubmitError": "Nie udało się zgłosić incydentu. Spróbuj ponownie."
    },

    "AssetTracking": {
      "NoPermission": "Nie masz uprawnień do sekcji Śledzenie zasobów. Tylko administratorzy i menedżerowie mogą przypisywać zasoby.",
      "SelectEmployee": "Wybierz pracownika",
      "PlaceholderSelectEmployee": "Wybierz pracownika, aby zobaczyć zasoby",
      "CurrentlyAssignedTo": "Obecnie przypisane do {0}",
      "ColAssetName": "Nazwa zasobu",
      "ColType": "Typ",
      "ColSerialNumber": "Numer seryjny",
      "ColStatus": "Status",
      "ColAssignedDate": "Data przypisania",
      "NotAvailable": "Nie dotyczy",
      "NoAssetsAssigned": "Ten pracownik nie ma obecnie przypisanych zasobów."
    },

    "ConfigPage": {
      "HeaderTitle": "Konfiguracja i zarządzanie listami",
      "HeaderSubtitle": "Centrum administracyjne do monitorowania list SharePoint, walidacji schematu, grup dostępu i konserwacji danych.",
      "TabSyncOperations": "Konserwacja",
      "TabListConnections": "Połączenia list",
      "TabRbacGroups": "Grupy dostępu",
      "TabSchemaGuides": "Walidacja schematu",
      "OperationsTitle": "Zarządzanie i synchronizacja listy mapowania",
      "OperationsDescBefore": "Upewnij się, że wszystkie zasoby obecnie przypisane do aktywnych pracowników są poprawnie zmapowane na liście SharePoint",
      "OperationsDescAfter": "Użyj poniższych przycisków, aby wykonać ręczne sprawdzenie synchronizacji lub zdiagnozować schemat bazy danych listy.",
      "SyncButtonProcessing": "Przetwarzanie...",
      "SyncButtonDefault": "Synchronizuj przypisane zasoby",
      "DiagnosticsButtonChecking": "Sprawdzanie schematu...",
      "DiagnosticsButtonDefault": "Uruchom diagnostykę schematu",
      "DiagnosticLogLabel": "Wynik dziennika diagnostycznego:",
      "ConnectionsTitle": "Połączenia list SharePoint",
      "ConnectionsDesc": "Każda lista jest wyszukiwana pod tymi samymi nazwami, których aplikacja używa w działaniu, a następnie sprawdzane są dostęp, Twoje uprawnienia i wymagane kolumny.",
      "ListTitle_InventoryList": "Lista inwentarza",
      "ListDesc_InventoryList": "Przechowuje główny katalog wszystkich zasobów fizycznych i sprzętu.",
      "ListTitle_RequestList": "Lista wniosków",
      "ListDesc_RequestList": "Zarządza zgłoszeniami pracowników, historią przepływów pracy i kolejkami przypisań.",
      "ListTitle_AssetReturnRequestList": "Lista wniosków o zwrot zasobów",
      "ListDesc_AssetReturnRequestList": "Obsługuje formularze zwrotu zasobów, kontrole przy zwrocie i zatwierdzenia przez menedżera.",
      "ListTitle_MappingList": "Lista mapowania",
      "ListDesc_MappingList": "Utrzymuje aktywne mapowanie przypisań w czasie rzeczywistym na potrzeby automatycznych kontroli zwolnienia.",
      "ErrorLabel": "Błąd:",
      "StatusVerifying": "Weryfikowanie...",
      "StatusConnected": "Połączono",
      "StatusFailed": "Niepowodzenie",
      "StatusNotVerified": "Niezweryfikowano",
      "TestLiveButton": "Testuj na żywo",
      "RbacTitle": "Kontrola dostępu oparta na rolach (RBAC)",
      "RbacDesc": "Sprawdź grupy użytkowników pobrane z SharePoint w celu weryfikacji poziomu uprawnień.",
      "RoleLabel_Owners": "Administrator",
      "RoleDesc_Owners": "Pełne uprawnienia administracyjne do modyfikowania zasobów, zatwierdzania zwrotów i zarządzania ustawieniami połączenia z bazą danych.",
      "RoleLabel_Members": "Menedżer inwentarza",
      "RoleDesc_Members": "Dostęp do zapisu w celu tworzenia elementów, przetwarzania zwrotów, przypisywania zasobów i przeglądania raportów.",
      "RoleLabel_Visitors": "Pracownik inwentarza",
      "RoleDesc_Visitors": "Dostęp tylko do odczytu dostępnych zapasów oraz uprawnienie do składania zgłoszeń zwrotu.",
      "ViewMembersButton": "Wyświetl członków",
      "LoadingButton": "Ładowanie...",
      "NoMembersFound": "Nie znaleziono członków w tej grupie",
      "SchemaTitle": "Wymagany schemat list",
      "SchemaDesc": "Kolumny, które musi zawierać każda lista. Po sprawdzeniu zielone kolumny znaleziono na liście, a czerwone są brakujące. Najedź na kolumnę, aby zobaczyć akceptowane nazwy alternatywne.",
      "SchemaAssetDatabase": "(Baza danych zasobów)",
      "SchemaApprovalWorkflows": "(Przepływy zatwierdzania)",
      "SchemaReturnsHandling": "(Obsługa zwrotów)",
      "SchemaCustodyTracking": "(Śledzenie posiadania)",
      "TabOverview": "Przegląd",
      "OverviewTitle": "Kondycja systemu",
      "LastChecked": "Ostatnie sprawdzenie: {0}",
      "NeverChecked": "Jeszcze nie sprawdzono",
      "RunHealthCheckButton": "Sprawdź kondycję",
      "RunningHealthCheck": "Sprawdzanie...",
      "ExportReportButton": "Eksportuj raport",
      "Tile_CoreLists": "Gotowe listy podstawowe",
      "Tile_SchemaIssues": "Brakujące kolumny",
      "Tile_PermissionIssues": "Listy bez prawa zapisu",
      "Tile_OptionalLists": "Znalezione listy opcjonalne",
      "IssuesTitle": "Wymagane działania",
      "ViewDetails": "Szczegóły",
      "NoIssues": "Wszystkie listy są połączone i mają oczekiwane kolumny oraz uprawnienia.",
      "EnvironmentTitle": "Środowisko",
      "Env_Site": "Witryna",
      "Env_User": "Zalogowano jako",
      "Env_SiteAdmin": "Administrator zbioru witryn",
      "Env_Language": "Język SharePoint",
      "Env_TotalLists": "Widoczne listy w witrynie",
      "Yes": "Tak",
      "No": "Nie",
      "Issue_Error": "{0}: {1}",
      "Issue_Missing": "{0}: nie znaleziono listy. Utwórz listę o nazwie \"{1}\" lub zmień nazwę istniejącej.",
      "Issue_AutoCreated": "{0}: jeszcze nie utworzono. Aplikacja utworzy ją automatycznie przy pierwszym użyciu.",
      "Issue_Columns": "{0}: brakujące kolumny ({1}): {2}",
      "Issue_Write": "{0}: Twoje konto nie może dodawać ani edytować elementów.",
      "StatusWarning": "Wymaga uwagi",
      "StatusMissing": "Nie znaleziono",
      "AccessReadWrite": "Odczyt i zapis",
      "AccessReadOnly": "Tylko odczyt",
      "AccessNone": "Brak dostępu",
      "OptionalBadge": "Opcjonalna",
      "AutoCreatedBadge": "Tworzona automatycznie",
      "Items": "Elementy:",
      "LastModified": "Ostatnia zmiana:",
      "Access": "Twój dostęp:",
      "Columns": "Kolumny:",
      "ColumnsSummary": "{0}/{1} obecnych",
      "ResponseTime": "Odpowiedź:",
      "OpenList": "Otwórz listę",
      "TriedNames": "Nazwy list wyszukiwane przez aplikację",
      "SimilarLists": "Podobne listy w tej witrynie",
      "RenameHint": "Jeśli jedna z nich jest właściwą listą, zmień jej nazwę na \"{0}\" w ustawieniach listy.",
      "MissingColumnsLabel": "Brakujące kolumny",
      "AllColumnsPresent": "Wszystkie wymagane kolumny są obecne.",
      "CoreListsGroup": "Listy podstawowe",
      "OptionalListsGroup": "Listy opcjonalne",
      "ListTitle_EventLogList": "Dziennik zdarzeń",
      "ListDesc_EventLogList": "Ścieżka audytu zmian zasobów, przejść cyklu życia i operacji administracyjnych. Wyświetlana w strumieniu zdarzeń.",
      "ListTitle_IncidentList": "Lista incydentów",
      "ListDesc_IncidentList": "Przechowuje zgłoszenia uszkodzeń, utraty i awarii zasobów.",
      "ListTitle_EmployeeList": "Lista pracowników",
      "ListDesc_EmployeeList": "Katalog pracowników używany do powiadomień i wyszukiwania incydentów.",
      "ListTitle_ReplacementList": "Wymiany zasobów",
      "ListDesc_ReplacementList": "Śledzi zasoby zastępcze wydane po incydentach.",
      "SchemaUnchecked": "Uruchom sprawdzenie, aby zweryfikować te kolumny na listach SharePoint.",
      "SchemaAliasesHint": "Akceptowane również: {0}",
      "SchemaAuditTrail": "(Ścieżka audytu)",
      "RbacRoleRule": "Każdy użytkownik otrzymuje najwyższą rolę spośród grup, do których należy.",
      "FilterMembersPlaceholder": "Filtruj członków...",
      "LoadAllGroupsButton": "Odśwież wszystko",
      "MemberCount": "Członkowie: {0}",
      "YouAreMember": "Jesteś członkiem",
      "GroupNotFound": "Ta grupa nie istnieje w witrynie, więc nikt nie może otrzymać tej roli, dopóki nie zostanie utworzona.",
      "GroupLoadError": "Nie można załadować członków: {0}",
      "OverviewSubtitle": "Sprawdza każdą listę SharePoint, kolumnę i uprawnienie, od których zależy aplikacja.",
      "OverallHealthy": "Wszystkie systemy działają",
      "OverallWarning": "Elementy wymagające uwagi: {0}",
      "OverallCritical": "Znalezione krytyczne problemy: {0}",
      "OverallHint": "Wybierz problem poniżej, aby przejść do danej listy."
    },

    "ReportsPage": {
      "HeaderTitle": "Raportowanie i statystyki",
      "HeaderSubtitle": "Interaktywne pulpity nawigacyjne, wykresy na żywo, analiza statusu i moduł eksportu.",
      "TabVisualInsights": "Statystyki wizualne",
      "TabDetailedReports": "Szczegółowe raporty",
      "TabWarrantyExpiry": "Wygaśnięcie gwarancji",
      "StatTotalAssets": "CAŁKOWITA LICZBA ZASOBÓW INWENTARZA",
      "StatAssetsAssigned": "OBECNIE PRZYPISANE ZASOBY",
      "StatUtilizationRate": "WSKAŹNIK WYKORZYSTANIA",
      "StatTotalRequests": "CAŁKOWITA LICZBA WNIOSKÓW O ZATWIERDZENIE",
      "ChartStatusDistribution": "Rozkład statusu zasobów",
      "DataLabelInStock": "W magazynie",
      "DataLabelAssigned": "Przypisane",
      "DataLabelPendingReturn": "Oczekujący zwrot",
      "DataLabelUnderMaintenance": "W konserwacji",
      "LegendInStock": "W magazynie",
      "LegendAssigned": "Przypisane",
      "LegendPendingReturn": "Oczekujący zwrot",
      "LegendMaintenance": "Konserwacja",
      "ChartTypeDistribution": "Rozkład typu zasobów",
      "ChartDatasetAssetsCount": "Liczba zasobów",
      "ChartAgingAnalysis": "Analiza wieku zasobów",
      "DataLabelAgingUnder1": "< 1 rok (nowy)",
      "DataLabelAging1to3": "1-3 lata",
      "DataLabelAgingOver3": "> 3 lata (starzejący się)",
      "DataLabelAgingUnknown": "Nieznany",
      "LegendAgingUnder1": "< 1 rok",
      "LegendAging1to3": "1-3 lata",
      "LegendAgingOver3": "> 3 lata",
      "LegendAgingUnknown": "Nieznany",
      "ChartRequestTrends": "Trendy zatwierdzania wniosków",
      "DataLabelApproved": "Zatwierdzone",
      "DataLabelDeclinedRejected": "Odrzucone/Odmówione",
      "DataLabelPending": "Oczekujące",
      "DetailedTitle": "Filtrowalny inwentarz zasobów",
      "ExportExcel": "Eksportuj Excel",
      "ExportPDF": "Eksportuj PDF",
      "LabelAssetType": "Typ zasobu",
      "FilterAllTypes": "Wszystkie typy",
      "LabelAssetStatus": "Status zasobu",
      "FilterAllStatuses": "Wszystkie statusy",
      "ColUnassigned": "Nieprzypisane",
      "WarrantyTitle": "Raport wygaśnięcia gwarancji",
      "TotalAssetsCountLabel": "Całkowita liczba zasobów",
      "AssetsWithWarrantyLabel": "Zasoby z danymi gwarancyjnymi",
      "ColWarrantyExpiryDate": "Data wygaśnięcia gwarancji",
      "WarrantyNotAvailable": "Nie dotyczy",
      "WarrantyExpiredTag": "(Wygasła)",
      "WarrantyActiveTag": "(Aktywna)"
    },

    "InventoryPage": {
      "Title": "Przegląd bieżącego inwentarza",
      "Description": "Śledź i zarządzaj zasobami swojej organizacji w sposób efektywny w ramach SharePoint Framework.",
      "LoadingInventory": "Ładowanie inwentarza...",
      "ButtonAddNewAsset": "Dodaj nowy zasób",
      "ButtonAssignManageAssets": "Przypisz / Zarządzaj zasobami"
    },

    "IncidentHistoryPage": {
      "Title": "Historia incydentów"
    },

    "RequestAnalysis": {
      "OverviewTitle": "Przegląd wniosku",
      "LabelRequestKey": "Klucz wniosku:",
      "LabelRequestedAsset": "Żądany zasób:",
      "LabelQuantity": "Ilość:",
      "LabelPriority": "Priorytet:",
      "LabelRequesterName": "Nazwa wnioskodawcy:",
      "LabelEmployeeId": "ID pracownika:",
      "LabelRequestDate": "Data wniosku:",
      "LabelRequestStatus": "Status wniosku:",
      "LabelReasonForRequest": "Powód wniosku:",
      "LabelManagerResponse": "Odpowiedź menedżera:",
      "DetailedAnalysisTitle": "Szczegółowa analiza",
      "InventoryCheckLabel": "Kontrola dostępności zapasów:",
      "InventoryCheckPassedBold": "Kontrola zapasów zaliczona:",
      "InventoryCheckPassedBefore": "Obecnie dostępnych jest",
      "InventoryCheckPassedMiddle": "jednostek(-a)",
      "InventoryCheckPassedAfter": "w magazynie, co jest wystarczające do realizacji tego wniosku.",
      "InventoryWarningBold": "Ostrzeżenie o zapasach:",
      "InventoryWarningBefore": "Tylko",
      "InventoryWarningMiddle": "jednostek(-a)",
      "InventoryWarningAfter": "w magazynie. Wymagane jest zamówienie, aby w pełni zrealizować to zamówienie.",
      "StrategicRecommendationLabel": "Rekomendacja strategiczna:",
      "RecommendedActionBold": "Zalecana czynność:",
      "RecommendationApproveSufficient": "Zatwierdź wniosek. Dostępne są wystarczające zapasy, co umożliwia natychmiastowe przypisanie numeru seryjnego.",
      "RecommendationHoldBefore": "Wstrzymaj zatwierdzenie lub przypisz model alternatywny. Obecny zapas (",
      "RecommendationHoldAfter": ") jest niewystarczający. Zamów jednostki uzupełniające.",
      "RecommendationAssignBefore": "Przejdź do karty",
      "RecommendationAssignQueueLabel": "Kolejka przypisania zasobów",
      "RecommendationAssignMiddle": "aby przydzielić jeden z",
      "RecommendationAssignAfter": "dostępnych {0} dla {1}.",
      "LifecycleCompleteBold": "Cykl życia zakończony:",
      "LifecycleCompleteText": "Zasób został pomyślnie przydzielony. Nie jest wymagana dalsza czynność menedżera ani administratora.",
      "ClosedBold": "Zamknięte:",
      "ClosedText": "Wniosek został odrzucony. Zrealizuj alternatywne opcje lub przejrzyj argumenty w przypadku odwołania.",
      "LifecycleStageLabel": "Etap cyklu życia wniosku:",
      "StepSubmittedPending": "Złożony i oczekujący na zatwierdzenie",
      "StepManagerApproved": "Zatwierdzony przez menedżera - oczekuje na przypisanie zasobu",
      "StepCompleted": "Zakończony i zasób przypisany",
      "StepDeclined": "Odrzucony przez menedżera"
    },

    "AssetAnalysis": {
      "SpecificationsTitle": "Specyfikacje zasobu",
      "LabelAssetName": "Nazwa zasobu:",
      "LabelSerialNumber": "Numer seryjny:",
      "LabelAssetType": "Typ zasobu:",
      "LabelCurrentStatus": "Bieżący status:",
      "LabelCondition": "Stan:",
      "LabelVendor": "Dostawca:",
      "LabelPurchaseDate": "Data zakupu:",
      "LabelWarrantyExpiry": "Wygaśnięcie gwarancji:",
      "LabelAssetNotes": "Uwagi dotyczące zasobu:",
      "DetailedAnalysisTitle": "Analiza kondycji i amortyzacji",
      "LifecycleEolLabel": "Cykl życia zasobu i data końca eksploatacji:",
      "LifecyclePurchaseDatePrefix": "Data zakupu:",
      "LifecycleEolDatePrefix": "Firmowa data końca eksploatacji:",
      "WarrantyEvaluationLabel": "Ocena wygaśnięcia gwarancji:",
      "WarrantyExpiredBold": "Gwarancja wygasła:",
      "WarrantyExpiredBefore": "Ochrona zakończyła się",
      "WarrantyExpiredAfter": "Wszelkie przyszłe naprawy będą wiązać się z pełnymi bezpośrednimi kosztami biznesowymi.",
      "WarrantyExpiringSoonBold": "Gwarancja wkrótce wygaśnie (< 6 miesięcy):",
      "WarrantyExpiringSoonBefore": "Data wygaśnięcia to",
      "WarrantyExpiringSoonAfter": "Wysoki priorytet dla odnowienia sprzętu/gwarancji.",
      "WarrantyExpiring1YearBold": "Gwarancja wygasa (< 1 rok):",
      "WarrantyExpiring1YearBefore": "Data wygaśnięcia to",
      "WarrantyExpiring1YearAfter": "Zaplanuj nadchodzące zarządzanie cyklem życia sprzętu.",
      "WarrantyActiveBold": "Gwarancja aktywna (> 1 rok):",
      "WarrantyActiveBefore": "Pełna ochrona producenta do",
      "WarrantyActiveAfter": "",
      "WarrantyUnknownBold": "Gwarancja nieznana:",
      "WarrantyUnknownText": "Nie zarejestrowano daty wygaśnięcia gwarancji dla tego zasobu.",
      "PhysicalHealthLabel": "Stan fizyczny zasobu:",
      "HealthClassificationLabel": "Klasyfikacja kondycji:",
      "CriticalActionRecommendation": "Zalecenie krytycznej czynności: Zdecydowanie zaleca się wycofanie tego zasobu i złożenie wniosku o wymianę.",
      "HealthExcellent": "Doskonały",
      "HealthFair": "Dostateczny",
      "HealthCritical": "Krytyczny, wymaga wymiany"
    },

    "NotificationDetailsPanel": {
      "LabelReceived": "Otrzymano:",
      "SystemAlertTitle": "Analiza alertu systemowego",
      "GeneralNotificationText": "To jest ogólne powiadomienie systemowe. Nie ma bezpośredniego połączenia z bazą danych do aktywnego wniosku lub zasobu."
    },

    "AdminAssignmentPanel": {
      "RequestHeaderPrefix": "Wniosek #",
      "SubHeader": "Szczegóły wniosku o zasób",
      "RequestInfoTitle": "Informacje o wniosku",
      "BadgePendingAdmin": "Oczekuje na administratora",
      "LabelCategory": "Kategoria",
      "LabelQuantity": "Ilość",
      "LabelUrgency": "Pilność",
      "LabelSubmitted": "Złożono",
      "LabelJustification": "Uzasadnienie",
      "ApprovalTrailTitle": "Ścieżka zatwierdzania",
      "StepSubmitted": "Złożono",
      "StepManagerReview": "Weryfikacja menedżera",
      "ManagerReviewDefaultQuote": "Zatwierdzono - uzasadniona potrzeba biznesowa",
      "StepAdminAssignment": "Przypisanie przez administratora",
      "AwaitingAllocation": "Oczekuje na przydzielenie zasobu",
      "AdminAssignmentTitle": "Przypisanie przez administratora",
      "LabelAssignAssetOptional": "Przypisz zasób (opcjonalnie)",
      "PlaceholderSelectAsset": "Wybierz zasób do przypisania...",
      "PlaceholderNoAssetsInStock": "Brak zasobów tego typu w magazynie",
      "LabelComment": "Komentarz",
      "PlaceholderComment": "Dodaj komentarz wyjaśniający swoją decyzję...",
      "ButtonProcessing": "Przetwarzanie...",
      "ButtonAssignApprove": "Przypisz i zatwierdź",
      "ButtonReject": "Odrzuć"
    },

    "MyWorkspacePage": {
      "Title": "Moje miejsce pracy",
      "Description": "Zarządzaj przypisanymi zasobami i śledź swoje wnioski.",
      "TabsAriaLabel": "Karty Moje miejsce pracy",
      "TabAssets": "Zasoby",
      "ButtonRequestAsset": "Złóż wniosek o zasób",
      "TabRequests": "Wnioski"
    },

    "ApprovalsPage": {
      "Title": "Zatwierdzenia wniosków i kolejka przypisań",
      "Description": "Efektywnie śledź i zarządzaj wszystkimi wnioskami o zasoby.",
      "SearchLabel": "Szukaj według ID wniosku",
      "SearchPlaceholder": "np. REQ-000123",
      "ChartTitle": "Rozkład zatwierdzeń wniosków",
      "ChartDatasetLabel": "Wnioski według statusu",
      "NoDataLabel": "Brak danych"
    },

    "AssetAssignmentQueuePage": {
      "Title": "Zatwierdzone wnioski do przypisania zasobu",
      "Description": "Tutaj wyświetlane są tylko zatwierdzone wnioski, aby można było przypisać zasoby."
    },

    "AssetReturnsPage": {
      "Title": "Rejestr zwrotów zasobów",
      "Description": "Przeglądaj i finalizuj wnioski pracowników o zwrot zasobów oraz weryfikuj fizyczne zwroty sprzętu."
    },

    "UsersPage": {
      "Title": "Administracja użytkownikami",
      "Description": "Obszar wyłącznie dla administratorów. Zarządzaj grupami SharePoint i wdrażaniem użytkowników na podstawie uprawnień witryny.",
      "GroupManagementTitle": "Zarządzanie grupami SharePoint",
      "GroupManagementDesc": "Aby wdrożyć nowych pracowników, przyznać im dostęp administratora lub przypisać ich jako menedżerów inwentarza, musisz dodać ich do odpowiednich grup witryny SharePoint.",
      "ManageSitePermissionsButton": "Zarządzaj uprawnieniami witryny",
      "DirectoryTitle": "Katalog pracowników i własność zasobów",
      "ColName": "Imię i nazwisko",
      "ColEmail": "E-mail",
      "ColDepartment": "Dział",
      "ColJobTitle": "Stanowisko",
      "ColAssignedAssets": "Przypisane zasoby",
      "ColAssetTypes": "Typy zasobów",
      "AssetTypesNone": "Brak",
      "AssetsAssignedToPrefix": "Zasoby przypisane do",
      "NoAssetsAssignedToUser": "Ten użytkownik nie ma obecnie przypisanych zasobów.",
      "EmployeeTrackingTitle": "Śledzenie zasobów pracowników",
      "EmployeeTrackingDesc": "Obszar administratora i menedżera. Wybierz pracownika, aby zobaczyć wszystkie zasoby obecnie mu przypisane."
    },

    "MockEmailPanel": {
      "HeaderText": "📬 Powiadomienie o wychodzącej wiadomości e-mail (podgląd deweloperski)",
      "ButtonSending": "Wysyłanie...",
      "ButtonSendEmail": "Wyślij e-mail",
      "ButtonClose": "Zamknij",
      "InfoText": "Możesz przejrzeć, zmodyfikować odbiorcę(-ów) lub temat i wysłać tę wiadomość e-mail w celu przetestowania dostarczenia.",
      "LabelRecipients": "Odbiorcy (oddzieleni przecinkami)",
      "LabelSubject": "Temat",
      "SuccessText": "Wiadomość e-mail została pomyślnie wysłana do kolejki poczty Microsoft Graph / SharePoint!",
      "ErrorPrefix": "Nie udało się wysłać wiadomości e-mail:",
      "ProgressLabel": "Trwa transakcja wysyłki wiadomości e-mail...",
      "PreviewLabel": "Podgląd treści wiadomości e-mail:"
    },

    "IncidentSuccessPopup": {
      "Title": "Zgłoszenie incydentu zarejestrowane",
      "Stage": "Zarządzanie incydentami: Zarejestrowano",
      "Message": "Zgłoszenie incydentu dla \"{0}\" ({1}) zostało zarejestrowane i przypisane do wsparcia IT administratora.",
      "StatusOpenTicket": "Otwarte zgłoszenie"
    },

    "WarrantyUtils": {
      "NotAvailable": "Nie dotyczy",
      "NoWarrantyDate": "brak daty gwarancji",
      "InvalidDate": "nieprawidłowa data",
      "DaysAgoSingular": "{0} dzień temu",
      "DaysAgoPlural": "{0} dni temu",
      "DaysRemainingSingular": "pozostał {0} dzień",
      "DaysRemainingPlural": "pozostało {0} dni",
      "UnknownPurchaseDate": "Nieznana data zakupu",
      "InvalidPurchaseDate": "Nieprawidłowa data zakupu",
      "StatusEol": "Zasób osiągnął koniec cyklu życia (EOL)",
      "StatusActive": "Zasób znajduje się w aktywnym cyklu życia w przedsiębiorstwie"
    },

    "Columns": {
      "Id": "ID",
      "Title": "Tytuł",
      "AssetName": "Nazwa zasobu",
      "Type": "Typ",
      "SerialNumber": "Numer seryjny",
      "PurchaseDate": "Data zakupu",
      "Vendor": "Dostawca",
      "Condition": "Stan",
      "WarrantyExpiry": "Wygaśnięcie gwarancji",
      "Status": "Status",
      "AssignedTo": "Przypisano do",
      "Specifications": "Specyfikacja",
      "Actions": "Akcje",
      "ActivationState": "Stan aktywacji",
      "RequestId": "ID wniosku",
      "EmployeeName": "Imię i nazwisko pracownika",
      "ManagerName": "Imię i nazwisko kierownika",
      "AssetType": "Typ zasobu",
      "Priority": "Priorytet",
      "ManagerComment": "Komentarz kierownika",
      "AssetStatus": "Status zasobu",
      "AdminResponse": "Odpowiedź administratora",
      "RequestedDate": "Data wniosku",
      "Reason": "Powód",
      "ManagerNotes": "Uwagi kierownika"
    },

    "Pagination": {
      "ShowingEntries": "Wyświetlanie {0} do {1} z {2} pozycji",
      "FirstPage": "Pierwsza strona",
      "PreviousPage": "Poprzednia strona",
      "NextPage": "Następna strona",
      "LastPage": "Ostatnia strona"
    },

    "InventoryList": {
      "ActivationDeactivated": "Dezaktywowany",
      "ActivationActivated": "Aktywowany",
      "ActivationInactivated": "Nieaktywny",
      "ActionPendingReturn": "Oczekuje na zwrot",
      "ActionApproved": "Zatwierdzono",
      "ActionReturn": "Zwróć"
    },

    "EventStream": {
      "NoticeLabel": "Uwaga:",
      "ColumnAction": "Akcja",
      "ColumnUser": "Użytkownik",
      "ColumnTimestamp": "Znacznik czasu",
      "ColumnDetails": "Szczegóły",
      "LoadingAuditLogs": "Ładowanie dzienników zdarzeń...",
      "NoEventsForYou": "Nie zarejestrowano jeszcze żadnych zdarzeń audytu dla Ciebie.",
      "NoEventsRecorded": "Nie zarejestrowano jeszcze żadnych zdarzeń audytu.",
      "NoEventsMatchFilters": "Żadne zdarzenia audytu nie pasują do aktywnych filtrów.",
      "ActionCreated": "utworzono",
      "ActionManagerApproved": "zatwierdzone przez kierownika",
      "ActionManagerRejected": "odrzucone przez kierownika",
      "ActionAdminAssigned": "przydzielone przez administratora",
      "ActionInProgress": "status zmieniony na w toku",
      "ActionResolved": "status zmieniony na rozwiązane",
      "ActionDeleted": "usunięto",
      "ActionReturnRequested": "zgłoszono zwrot",
      "ActionReturnApproved": "zatwierdzono zwrot",
      "ActionReturnCompleted": "zakończono zwrot",
      "ActionReturnRejected": "odrzucono zwrot",
      "ActionActivated": "aktywowano",
      "ActionInactivated": "dezaktywowano",
      "ActionDeactivated": "wyłączono",
      "ActionUpdated": "zaktualizowano"
    },

    "EventFilters": {
      "SearchPlaceholder": "Szukaj według nazwy zasobu, tytułu, szczegółów, użytkownika lub akcji...",
      "LabelDateRange": "Zakres dat",
      "LabelAction": "Akcja",
      "LabelModule": "Moduł",
      "LabelAssetType": "Typ zasobu",
      "LabelUser": "Użytkownik",
      "LabelStatus": "Status",
      "LabelSortOrder": "Kolejność sortowania",
      "LabelStartDate": "Data początkowa",
      "LabelEndDate": "Data końcowa",
      "StartDatePlaceholder": "Wybierz datę początkową...",
      "EndDatePlaceholder": "Wybierz datę końcową...",
      "DateRangeWarning": "Ostrzeżenie: Data początkowa musi być wcześniejsza lub równa dacie końcowej.",
      "ActiveFilters": "Aktywne filtry:",
      "ClearAll": "Wyczyść wszystko",
      "ChipAction": "Akcja: {0}",
      "ChipModule": "Moduł: {0}",
      "ChipAsset": "Zasób: {0}",
      "ChipUser": "Użytkownik: {0}",
      "ChipStatus": "Status: {0}",
      "AllActionsOption": "Wszystkie akcje",
      "AllAssetsOption": "Wszystkie zasoby",
      "AllUsersOption": "Wszyscy użytkownicy"
    },

    "RequestList": {
      "StatusPendingManagerApproval": "Oczekuje na zatwierdzenie przez kierownika",
      "ButtonReviewAssign": "Przejrzyj i przydziel",
      "NoAction": "Brak działania",
      "RejectionPrompt": "Podaj powód odrzucenia tego wniosku:",
      "AdminResponseWaitingOnManager": "Oczekuje na kierownika",
      "AdminResponseRejected": "Nie dotyczy (odrzucono)",
      "AdminResponseAllocated": "Zasób przydzielony",
      "AdminResponsePendingApproval": "Oczekuje na zatwierdzenie administratora",
      "EmptyState": "Nie znaleziono wniosków o zasoby.",
      "DetailsHeaderPrefix": "Szczegóły wniosku: {0}",
      "DetailsHeaderFallback": "Wniosek o zasób",
      "SectionRequestInformation": "Informacje o wniosku",
      "LabelRequestDate": "Data wniosku",
      "LabelAssetCategory": "Kategoria zasobu",
      "SectionJustification": "Uzasadnienie / Powód",
      "SectionManagerApproval": "Zatwierdzenie kierownika",
      "SectionAdminAllocation": "Przydział administratora",
      "AllocationAllocated": "Zasób przydzielony i wysłany ✓",
      "AllocationPendingAdmin": "Oczekuje na fizyczny przydział zasobu przez administratora systemu",
      "AllocationNotApplicable": "Nie dotyczy (wniosek został odrzucony przez kierownika)",
      "AllocationPendingManager": "Oczekuje najpierw na zatwierdzenie przez kierownika"
    },

    "ReturnRequestList": {
      "SearchPlaceholder": "Szukaj wniosków o zwrot...",
      "ColId": "ID",
      "ColEmployee": "Pracownik",
      "ColReason": "Powód",
      "EmptyState": "Nie znaleziono wniosków o zwrot.",
      "DialogTitleApprove": "Zatwierdź wniosek o zwrot",
      "DialogTitleReject": "Odrzuć wniosek o zwrot",
      "DialogTitleComplete": "Zweryfikuj i zakończ zwrot",
      "DialogTitleView": "Szczegóły wniosku o zwrot",
      "DialogSubtext": "Wniosek złożony przez {0} dotyczący zasobu {1}",
      "AlertRejectionRequired": "Podaj powód/komentarz odrzucenia.",
      "AlertVerificationRequired": "Podaj komentarz weryfikacyjny.",
      "AlertActionFailedPrefix": "Działanie nie powiodło się:",
      "CardTitle": "Szczegóły zwrotu zasobu",
      "LabelProposedCondition": "Proponowany stan",
      "LabelFinalCondition": "Ostateczny zweryfikowany stan",
      "LabelReturnReason": "Powód zwrotu",
      "LabelRejectionReason": "Powód odrzucenia (wymagane)",
      "LabelVerificationComments": "Komentarze weryfikacyjne (wymagane)",
      "LabelManagerComments": "Komentarze kierownika",
      "PlaceholderRejectionReason": "Podaj, dlaczego ten wniosek o zwrot jest odrzucany...",
      "PlaceholderVerificationComments": "Wprowadź szczegóły weryfikacji (wymagane)...",
      "PlaceholderManagerComments": "Dodaj komentarze do wniosku o zwrot...",
      "ButtonApprove": "Zatwierdź",
      "ButtonReject": "Odrzuć",
      "ButtonVerifyComplete": "Zweryfikuj i zakończ",
      "None": "Brak",
      "StatusPendingAdminVerification": "Oczekuje na weryfikację administratora",
      "LoadingReturnRequests": "Ładowanie wniosków o zwrot..."
    },

    "AssetHealth": {
      "MetricAssignedAssets": "Przydzielone zasoby",
      "MetricUnderWarranty": "Na gwarancji",
      "MetricWarrantyAction": "Działanie gwarancyjne",
      "MetricCriticalAlerts": "Alerty krytyczne",
      "SearchPlaceholder": "Szukaj według nazwy zasobu, typu, numeru seryjnego...",
      "AllTypesOption": "Wszystkie typy",
      "AllConditionsOption": "Wszystkie stany",
      "AllCoverageOption": "Wszystkie pokrycia",
      "WarrantyNoneRegistered": "brak daty gwarancji",
      "WarrantyInvalidDate": "Nieprawidłowa data",
      "WarrantyExpiringSoonDays": "Wkrótce wygasa ({0} dni)",
      "WarrantyActive": "Aktywna",
      "BadgeIssueActive": "Aktywne zgłoszenie",
      "BadgeReplacementRequested": "Wniosek o wymianę",
      "SerialNumberPrefix": "Nr seryjny:",
      "PurchasedPrefix": "Zakupiono:",
      "AgePrefix": "Wiek:",
      "AgeSuffix": "mies.",
      "RefreshEligible": "(Kwalifikuje się do wymiany ⚠️)",
      "WarrantyExpiredStrip": "Gwarancja wygasła:",
      "WarrantyExpiringStrip": "Gwarancja wygasa:",
      "WarrantyActiveStrip": "Gwarancja aktywna (wygasa: {0})",
      "ButtonDetails": "Szczegóły",
      "ButtonReportIssue": "Zgłoś problem",
      "ButtonAssetReplacement": "Wymiana zasobu",
      "ButtonPendingReturn": "Oczekuje na zwrot",
      "ButtonApprovedBadge": "Zatwierdzono",
      "ButtonReturn": "Zwróć",
      "EmptyStateTitle": "Nie znaleziono przydzielonych zasobów",
      "EmptyStateHint": "Spróbuj dostosować zapytanie wyszukiwania lub filtry.",
      "DetailsHeaderPrefix": "Szczegóły zasobu: {0}",
      "LabelAssetType": "Typ zasobu:",
      "LabelVendorBrand": "Dostawca/Marka:",
      "LabelSerialNumber": "Numer seryjny:",
      "LabelAssetStatus": "Status zasobu:",
      "LabelTitleDescription": "Opis tytułu:",
      "LifecycleReportTitle": "Raport cyklu życia i stanu",
      "LifecycleAgeLabel": "Wiek zasobu w cyklu życia",
      "LifecycleAgeText": "Ten zasób ma {0} mies. (lata: {1}). Standardowy cykl amortyzacji w przedsiębiorstwie to 36 miesięcy.",
      "LifecycleRefreshWarning": "⚠️ Zasób osiągnął/przekroczył standardowy 3-letni cykl życia. Kwalifikuje się do wymiany.",
      "LifecycleWithinLifecycle": "✓ Zasób mieści się w standardowym cyklu użytkowania (pozostało {0} mies.).",
      "LifecycleUnknownPurchaseDate": "Data zakupu nie została zarejestrowana. Nie można obliczyć wieku.",
      "WarrantyCoverageLabel": "Pokrycie gwarancyjne",
      "WarrantyExpiredMessage": "Gwarancja wygasła: Ochrona zakończyła się {0}. Przyszłe naprawy zostaną obciążone kosztami działu.",
      "WarrantyExpiringSoonMessage": "Gwarancja wkrótce wygasa: Wygasa {0}. Zaplanuj przegląd sprzętu przed wygaśnięciem.",
      "WarrantyActiveMessage": "Gwarancja aktywna: Pełna ochrona do {0}.",
      "WarrantyUnknownMessage": "Gwarancja nieznana: Brak zarejestrowanej daty wygaśnięcia gwarancji dla tej pozycji.",
      "PhysicalConditionLabel": "Stan fizyczny",
      "HealthRatingLabel": "Ocena stanu:",
      "RetireRecommendationTitle": "Zalecenie: WYCOFAJ ZASÓB",
      "RetireRecommendationText": "Ponieważ ten zasób jest w stanie {0}, zaleca się zwrot zasobu i złożenie wniosku o wymianę.",
      "SystemSpecificationsLabel": "Specyfikacja systemu",
      "ButtonReportIncident": "Zgłoś incydent",
      "ButtonRequestReturn": "Wniosek o zwrot",
      "HealthExcellent": "Doskonały",
      "HealthSatisfactory": "Zadowalający",
      "HealthDegraded": "Pogorszony",
      "HealthUnusable": "Nieużywalny / Zepsuty"
    },

    "MyRequests": {
      "PivotAriaLabel": "Moje wnioski",
      "TabAssetRequests": "Wnioski o zasoby",
      "TabReturnRequests": "Wnioski o zwrot",
      "MetricTotalRequests": "Wszystkie wnioski",
      "MetricPendingApproval": "Oczekuje na zatwierdzenie",
      "MetricApproved": "Zatwierdzone",
      "MetricDeclined": "Odrzucone",
      "AllPrioritiesOption": "Wszystkie priorytety",
      "SearchAssetRequestsPlaceholder": "Szukaj według ID wniosku, typu zasobu, powodu...",
      "SearchReturnRequestsPlaceholder": "Szukaj według nazwy zasobu, numeru seryjnego, powodu...",
      "RequestedPrefix": "Żądano: {0}",
      "QtyLabel": "Ilość",
      "ManagerLabel": "Kierownik:",
      "ManagerPrefix": "Kierownik: {0}",
      "ReasonPrefix": "Powód: {0}",
      "ManagerNoteLabel": "Uwaga kierownika:",
      "ManagerNotePrefix": "Uwaga kierownika: {0}",
      "WaitingOnManager": "Oczekuje na kierownika",
      "NotApplicableRejected": "Nie dotyczy (odrzucono)",
      "AssetAllocatedCheck": "Zasób przydzielony ✓",
      "PendingAdminAllocation": "Oczekuje na przydział administratora",
      "EmptyAssetRequestsTitle": "Nie znaleziono wniosków o zasoby",
      "EmptyFilterHint": "Spróbuj dostosować zapytanie wyszukiwania lub filtry.",
      "MetricTotal": "Razem",
      "MetricPending": "Oczekujące",
      "MetricCompleted": "Zakończone",
      "MetricRejected": "Odrzucone",
      "SubmittedPrefix": "Nr seryjny: {0} • Złożono: {1}",
      "ManagerNotesLabel": "Uwagi kierownika:",
      "AwaitingManagerReview": "Oczekuje na przegląd kierownika",
      "HandoverToItTeam": "Proszę fizycznie przekazać zasób zespołowi IT",
      "EmptyReturnRequestsTitle": "Nie znaleziono wniosków o zwrot",
      "EmptyReturnRequestsHint": "Nie złożono jeszcze żadnych wniosków o zwrot. Użyj przycisku „Zwróć” przy zasobie w sekcji Moje zasoby.",
      "DetailsHeaderPrefix": "Szczegóły wniosku: {0}",
      "FallbackAssetRequest": "Wniosek o zasób",
      "LabelRequestId": "ID wniosku:",
      "LabelDateRequested": "Data wniosku:",
      "LabelRequester": "Wnioskodawca:",
      "LabelEmployeeId": "Numer pracownika:",
      "LabelAssetType": "Typ zasobu:",
      "LabelQuantity": "Ilość:",
      "ReasonForRequestTitle": "Powód wniosku",
      "NoReasonProvided": "Nie podano powodu.",
      "ManagerApprovalStatusTitle": "Status zatwierdzenia przez kierownika",
      "AdminAllocationStatusTitle": "Status przydziału administratora",
      "ReturnRequestDetailsPrefix": "Wniosek o zwrot: {0}",
      "StatusPendingSubmitted": "Twój wniosek o zwrot został złożony i oczekuje na przegląd kierownika.",
      "StatusPendingAdminMsg": "Twój zwrot został zatwierdzony przez kierownika i oczekuje na ostateczną weryfikację przez administratora IT.",
      "StatusApprovedCompleted": "Twój zwrot został zatwierdzony i zakończony. Zasób został przyjęty.",
      "StatusRejectedMsg": "Twój wniosek o zwrot został odrzucony. Sprawdź uwagi kierownika poniżej.",
      "StatusCompletedMsg": "Zasób został pomyślnie przyjęty. Ten zwrot jest zakończony.",
      "LabelAssetName": "Nazwa zasobu:",
      "LabelSerialNumber": "Numer seryjny:",
      "LabelSubmittedOn": "Złożono:",
      "LabelProposedCondition": "Proponowany stan:",
      "LabelCompletedOn": "Zakończono:",
      "ReasonForReturnTitle": "Powód zwrotu",
      "NoReasonProvidedReturn": "Nie podano powodu.",
      "ProgressTitle": "Postęp procesu zwrotu",
      "ProgressSubmitted": "Zwrot złożony",
      "ProgressManagerReview": "Przegląd kierownika",
      "ProgressHandoverVerification": "Fizyczne przekazanie zasobu i weryfikacja administratora"
    },

    "IncidentHistory": {
      "SearchIncidentsPlaceholder": "Szukaj według ID zgłoszenia, nazwy zasobu lub typu problemu...",
      "SearchReplacementsPlaceholder": "Szukaj według ID wymiany, nazwy zasobu...",
      "FilterByStatusPlaceholder": "Filtruj według statusu",
      "AllStatusOption": "Wszystkie statusy",
      "ShowingIncidents": "Wyświetlanie {0} z {1} zgłoszeń",
      "ShowingReplacements": "Wyświetlanie {0} z {1} wniosków o wymianę",
      "ColIncidentId": "ID zgłoszenia",
      "ColReplacementId": "ID wymiany",
      "ColAsset": "Zasób",
      "ColIssueType": "Typ problemu",
      "ColType": "Typ",
      "ReplacementRequestType": "Wniosek o wymianę",
      "ColPriority": "Priorytet",
      "ColStatus": "Status",
      "ColReported": "Zgłoszono",
      "ColActions": "Akcje",
      "ButtonView": "Podgląd",
      "ButtonDownload": "Pobierz",
      "NoIncidentsFound": "Nie znaleziono zgłoszeń.",
      "NoReplacementsFound": "Nie znaleziono wniosków o wymianę.",
      "IncidentDetailsTitle": "Szczegóły zgłoszenia",
      "ReplacementDetailsTitle": "Szczegóły wniosku o wymianę",
      "ReportedLabel": "Zgłoszono:",
      "IncidentSpecificationsTitle": "Specyfikacja zgłoszenia",
      "ReplacementSpecificationsTitle": "Specyfikacja wymiany",
      "LabelIncidentId": "ID zgłoszenia:",
      "LabelReplacementId": "ID wymiany:",
      "LabelAssetName": "Nazwa zasobu:",
      "LabelIssueType": "Typ problemu:",
      "LabelType": "Typ:",
      "LabelPriority": "Priorytet:",
      "LabelStatus": "Status:",
      "LabelAssignedTo": "Przypisano do:",
      "UpdateResolutionTitle": "Aktualizuj szczegóły rozwiązania",
      "LabelResolvedDate": "Data rozwiązania:",
      "ResolutionSummaryLabel": "Podsumowanie rozwiązania",
      "ResolutionSummaryPlaceholderIncident": "Opisz, jak rozwiązano ten problem...",
      "ResolutionSummaryPlaceholderReplacement": "Opisz, jak zrealizowano tę wymianę...",
      "SaveResolutionButton": "Zapisz rozwiązanie",
      "ResolutionDetailsTitle": "Szczegóły rozwiązania",
      "ResolutionSummaryPrefix": "Podsumowanie rozwiązania:",
      "ToastIncidentUpdatedTitle": "Zgłoszenie zaktualizowane",
      "ToastStatusUpdatedTitle": "Status zaktualizowany",
      "ToastResolutionSavedTitle": "Rozwiązanie zapisane",
      "ToastStatusMessage": "Status zgłoszenia {0} zmieniono na „{1}”.",
      "ToastResolutionMessage": "Zapisano podsumowanie rozwiązania dla zgłoszenia {0}.",
      "PdfCompanyHeader": "MSFT ZARZĄDZANIE INWENTARZEM",
      "PdfIncidentReportTitle": "RAPORT ZGŁOSZENIA",
      "PdfReplacementReportTitle": "RAPORT WYMIANY ZASOBU",
      "PdfGeneratedOn": "Wygenerowano: {0}",
      "PdfIncidentSpecs": "SPECYFIKACJA ZGŁOSZENIA",
      "PdfReplacementSpecs": "SPECYFIKACJA WYMIANY",
      "PdfIncidentIdLabel": "ID zgłoszenia:",
      "PdfReplacementIdLabel": "ID wymiany:",
      "PdfAssetNameLabel": "Nazwa zasobu:",
      "PdfIssueTypeLabel": "Typ problemu:",
      "PdfTypeLabel": "Typ:",
      "PdfPriorityLabel": "Priorytet:",
      "PdfCurrentStatusLabel": "Aktualny status:",
      "PdfReportedDateLabel": "Data zgłoszenia:",
      "PdfAssignedToLabel": "Przypisano do:",
      "PdfResolvedDateLabel": "Data rozwiązania:",
      "PdfIssueDescriptionTitle": "OPIS PROBLEMU",
      "PdfReplacementReasonTitle": "POWÓD I SZCZEGÓŁY WYMIANY",
      "PdfNoDescription": "Nie podano opisu.",
      "PdfNoReason": "Nie podano powodu.",
      "PdfResolutionSummaryTitle": "PODSUMOWANIE ROZWIĄZANIA"
    }
  }
});
