// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'filterDropdown': string;

  'filterSection': string;

  'filtersRow': string;

  'hide-on-mobile': string;

  'incidentHistory': string;

  'm-0': string;

  'mb-1': string;

  'mb-2': string;

  'mb-3': string;

  'mb-4': string;

  'mb-5': string;

  'metricDivider': string;

  'metricItem': string;

  'metricsRow': string;

  'mt-1': string;

  'mt-2': string;

  'mt-3': string;

  'mt-4': string;

  'mt-5': string;

  'p-0': string;

  'p-1': string;

  'p-2': string;

  'p-3': string;

  'p-4': string;

  'p-5': string;

  'searchField': string;

  'show-only-on-mobile': string;

  'statusBadge': string;

  'tableWrapper': string;

}

declare const strings: IExportStyles;

export default strings;