// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'filterSection': string;

  'replacementHistory': string;

  'statusBadge': string;

}

declare const strings: IExportStyles;

export default strings;